### ISSUE TITLE
Request: Add signal to identify LTN controled trains & if they are loading or unloading

### ISSUE THREAD

**Issue by penenkel** [Yousei9/Logistic-Train-Network#106]
I could use a signal at the train stop to indicate if the train currently halting is controlled (i.e. was planned) by the LTN as opposed to a player-controlled train, as I often use manually planned, automatic travel to reach far away outposts.

In addition to that I'd welcome an (easy) way to differentiate between an LTN-train there for loading or unloading.

Signal-wise I imagine this could be represented as either two binary signals (LTN/not-LTN and loading/unloading) or perhaps a three state signal with 1: LTN & loading, -1: LTN & unloading, 0: not-LTN.

What is your opinion on this? Btw. thank you for this great mod.

**Comment by Yousei9** [comment]
loading/unloading is defined by a trains schedule.
item > n means loading

**Comment by penenkel** [comment]
Hm, I have always used the difference between trainstop (train content) and yellow combinator (desired train content) signals to determine if items will be loaded or unloaded. Unfortunately that difference can change (and switch its sign!) while the train content is modified (especially if multiple inserters or stack sizes >1 are involved). To get around that I use an SR latch with some additional combinators to ensure that only the first state after arrival is used. That's just quite a lot of combinators and logic for some basic information, I was hoping this could be simplified with some buildin signals.

Also I'm still not sure how to detect if a train stopping at the station is part of the LTN or not. For now I'm using the signal  `encoded position of locomotive > 0` as a workaround but that only works because I use a FARL locomotive as my player-train instead of a vanilla locomotive.

**Comment by Yousei9** [comment]
I'll look into ways to signal parked train status. Perhaps using the blue signal similar to depots.

**Comment by Yousei9** [comment]
The lamp control color signal now changes from yellow to blue when an LTN contolled train is parking at an LTN stop.
It will still show the amount of inbound trains in the color value.
