### ISSUE TITLE
[1.7.4] Index nil at control.lua:952

### ISSUE THREAD

**Issue by mspielberg** [Yousei9/Logistic-Train-Network#107]
`13499.440 Error MainLoop.cpp:1019: Exception at tick 8552892: Error while running event LogisticTrainNetwork::on_tick (ID 0)
__LogisticTrainNetwork__/control.lua:952: attempt to index local 'stop' (a nil value)
`

Occurs after mining a logistics train stop that currently is providing goods via a positive input signal.
Removing the circuit connection before mining the stop prevents the crash. From a quick glance at the code,  the following code at line 955 checks whether `stop` is nil, but the call to `bit32.band()` occurs first and dereferences `stop` blindly. I can provide a save if desired. Thanks for the great mod!

**Comment by Yousei9** [comment]
Thanks for the report.

Fixed in 1.7.5.
