### ISSUE TITLE
Error with Personal Teleporter.

### ISSUE THREAD

**Issue by WhatheWorld** [Yousei9/Logistic-Train-Network#112]
you should do a name check not a type check when entity is renamed. I use a train stop to put a marker on the map and rename them based on user renaming them and placing the entity.

-Creator of Personal Teleporter.

![error](https://user-images.githubusercontent.com/15742686/38399564-c76de03e-3910-11e8-9bd0-5fda6826ffea.png)
https://github.com/Yousei9/Logistic-Train-Network/blob/d124f0c5afb1c319040ecba524ace8cafc81c861/control.lua#L764

**Comment by Yousei9** [comment]
You should properly handle creating, removing and renaming stops. Including firing events when you create something in scripts.

LTN works with any base or modded stops.
