### ISSUE TITLE
Failed to load mod after installation of Dectorio

### ISSUE THREAD

**Issue by LDVSOFT** [Yousei9/Logistic-Train-Network#113]
Cannot start the game after adding [Dectorio](https://github.com/jpanther/Dectorio) mod. It says:

> Failed to load mods: error in assignID, virtual-signal with name 'signal-light-grey' does not exist.
>
> Source: logistic-train-stop-input (lamp)

Is this on your end, or should we create an issue in Dectorio?

**Comment by Yousei9** [comment]
No idea why ltn shows up in the error message.
LTN isn't using 'signal-light-grey' nor does it iterate through virtual signals.

**Comment by LDVSOFT** [comment]
Ha, fine for you? Thanks then, really cool mod!
