### ISSUE TITLE
Error loading virtual signals when using DyWorld

### ISSUE THREAD

**Issue by AP-Hunt** [Yousei9/Logistic-Train-Network#116]
Under Factorio 0.16.45, LTN cannot be loaded whilst the DYWorld mod is also enabled, because of a missing property in the prototype of the virtual signals LTN introduces. (Extended `factorio-current` dump at the bottom of this issue)

>Error ModManager.cpp:1024: Error while loading virtual-signal prototype "LTN-dyworld-stone-locomotive" (virtual-signal): Key "icon_size" not found in property tree at ROOT.virtual-signal.LTN-dyworld-stone-locomotive

Having a look at the source, it looks like the property in question is commented out on line 44 of [`data-final-fixes.lua`](https://github.com/Yousei9/Logistic-Train-Network/blob/master/data-final-fixes.lua#L44). Before I submit a pull request to fix, do any contributors know if it was commented out for a reason? Will restoring the property introduce a more subtle bug?

--- 
Extended `factorio-current` dump
```
   0.166 Device reset internal.
   0.169 Desktop composition is active.
   0.169 Graphics settings preset: very-high
   0.170 Graphics options: [Graphics quality: high] [Video memory usage: high] [Light scale: 25%] [DXT: false] [Shader: 1]
   0.170                   [Parallel sprite loading: 1] [Max texture size: 0/8192] [Bmp cache: 0] [Sprite slicing: 1] [Low quality rotation: 0]
   0.368 Loading mod settings DyWorld 0.6.5 (settings.lua)
   0.368 Loading mod settings LogisticTrainNetwork 1.7.7 (settings.lua)
   0.376 Loading mod core 0.0.0 (data.lua)
   0.436 Loading mod base 0.16.45 (data.lua)
   0.844 Loading mod DyWorld 0.6.5 (data.lua)
   1.180 Loading mod LogisticTrainNetwork 1.7.7 (data.lua)
   1.520 Loading mod base 0.16.45 (data-updates.lua)
   1.816 Loading mod DyWorld 0.6.5 (data-updates.lua)
   2.333 Loading mod DyWorld 0.6.5 (data-final-fixes.lua)
   2.711 Loading mod LogisticTrainNetwork 1.7.7 (data-final-fixes.lua)
   2.715 Script @__LogisticTrainNetwork__/data-final-fixes.lua:110: [LTN] found 1747 items, 56 fluids, 26 locomotives, 3 wagons
   3.070 Checksum for core: 2616611262
   3.070 Checksum of base: 2290967896
   3.070 Checksum of DyWorld: 2882425988
   3.070 Checksum of LogisticTrainNetwork: 2620749778
   3.569 Error ModManager.cpp:1024: Error while loading virtual-signal prototype "LTN-dyworld-stone-locomotive" (virtual-signal): Key "icon_size" not found in property tree at ROOT.virtual-signal.LTN-dyworld-stone-locomotive
Modifications: LTN - Logistic Train Network
   3.702 Loaded shader file D:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
   3.704 Loaded shader file D:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
   3.705 Loaded shader file D:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
   3.707 Initial atlas bitmap size is 16384
   3.708 Created atlas bitmap 192x5 [none]
   3.708 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
   3.746 Sprites loaded
   3.746 Convert atlas 132x24 to: trilinear-filtering
   3.753 Custom inputs active: 0
   3.755 Factorio initialised
   3.757 Mods to disable:Failed to load mods: Error while loading virtual-signal prototype "LTN-dyworld-stone-locomotive" (virtual-signal): Key "icon_size" not found in property tree at ROOT.virtual-signal.LTN-dyworld-stone-locomotive
```

**Comment by Yousei9** [comment]
LTN works with any other mod adding locomotives or wagons, so DYWorld must be doing something weird to produce this crash.

**Comment by AP-Hunt** [comment]
I'll look in to what it is DYWorld might be doing, but the error is coming from Factorio core code (`ModManager.cpp:1024`). Looking at the line I identified above, I suspect the bug is caused by the addition of a virtual signal prototype based on an entity introduced by DyWorld, but I suspect it's not limited to DyWorld. 

I'll report back when I find out.

**Comment by Yousei9** [comment]
Yes, LTN is creating virtual signals for any train entity it finds.
I just looked into the icons array my script creates. Like I thought DYWorld doesn't include icon_size in it's own icons arrays.
Quite odd it doesn't crash by itself.

**Comment by AP-Hunt** [comment]
I've been looking at this for the last hour or so, and come to the same conclusion. To test, I went through DYWorld and added `icon_size = 32` to every related icon definition. After that, it loaded just fine.

I would assume that if Factorio sees an `icon_size` on an icon it will use it, regardless of it being defined on the root of the prototype. So I think we can probably call this issue closed, with that fix in place?

**Comment by Yousei9** [comment]
For now I'd say it's fixed.
Maybe root element size now works better than when Factorio introduced support for layering different sized icons. Otherwise I have to rewrite my icon generation into something a lot more complex.
