### ISSUE TITLE
[BUG] Factorio 0.16.51 Cannot interact with LTN signal input / output

### ISSUE THREAD

**Issue by jarquafelmu** [Yousei9/Logistic-Train-Network#125]
With only using creative mode 016 and LTN, I was able to reproduce the problem I was having by not being able to interact with the signal input / output.

[Save File](https://drive.google.com/open?id=1Tzj0KjiodpOF3VWNATvH3RD-lhQ3A0q1)
[Screenshots](https://imgur.com/a/ONdQvba)

**Comment by Yousei9** [comment]
Those entities are only for getting circuit signals in and out.
There is nothing for you to interact with.
