### ISSUE TITLE
Getting spammed with notifications "ltn-message.no-train-found-merged"

### ISSUE THREAD

**Issue by NochEinKamel** [Yousei9/Logistic-Train-Network#128]
Hi,

I've updated from 1.7.6 to 1.7.12 and now I'm getting spammed with ltn-message.no-train-found-merged messages with some weird numbers:
Kein Zug mit Länge zwischen 5 und 5 für den Transport von 96480 Stapeln in Netzwerken 0xffffffff in Depots gefunden.

Sometimes it goes minutes without message and then it spams 50 messages - around one per second.

I think it's oil - then the number and the no available train message could make sense.
Also sometimes it shows very small values like 41, 42, 43, 44 which would make sense it it's flame thrower tower ammunition.

So... the issue basically is
a) that the message doesn't tell me that it's a liquid train that's missing and
b) that the message is displayed way too often if the requester value changes

Thanks for listening and for making this mod 👍

**Comment by Yousei9** [comment]
1.7.7 added the network hex code to the message and moved it back into notification level.

The way my spam filter works makes it impossible to filter the ever changing stack/fluid numbers. So it always will see it as new message and post it.
Perhaps an update to the spam filter is in order.
