### ISSUE TITLE
Requestor Station Constant Combinator does not show requested Amount

### ISSUE THREAD

**Issue by Intemes** [Yousei9/Logistic-Train-Network#131]
Hi,

None of my requestor Stations Yellow LTN Combinators (Stop Output?) show the requested amount anymore.

![image](https://user-images.githubusercontent.com/8416625/43474212-835b5f32-94f2-11e8-9fd3-85e0dbd90c44.png)
(Dark Image because i had to Pause to get the Screenshot, sorry)

I have set Deliveries to be reset at requestor, but turning that of didn't change the behaviour.

LTN Version 1.7.13 with Factorio Version 0.16.51.

(Great mod btw!)

**Comment by Yousei9** [comment]
With a bug report like that all I can say is that it works for me.
https://forums.factorio.com/viewtopic.php?f=214&t=60889

**Comment by Yousei9** [comment]
When unloading the combinator only displays train composition and items that are NOT unloaded.
All other signals come from the train stop reading train inventory.
To see the merged signals look at the pole to the left of your position in your screenshot.

PS: You can clearly see the inserters working in the screenshot.
