### ISSUE TITLE
Output signal at the LTN station does not see content if condition "Cargo: {item} = 0" is used

### ISSUE THREAD

**Issue by AsandaNima** [Yousei9/Logistic-Train-Network#133]
When a schedule is generated LTN sets the a condition for the drop-off station "Cargo: {item} = 0".
This causes the output signal at that station to not be able to see and output the train content for further use with filter inserter, etc.

I tried this with manually created schedules and the automatically generated schedules. This is always the case.
If you change the condition from "Cargo: {item} = 0" to "Cargo: {item} <= 0" before the train reaches the station, the signal is outputed normally.

**Comment by Yousei9** [comment]
Cargo: {item} >= 0: loading 
filter inserter = stop output - combinator output

Cargo: {item} = 0: unloading
filter inserter = combinator output - stop output

Cargo: {item} <= 0: does not exist

**Comment by AsandaNima** [comment]
I'm not sure what you mean by "Cargo: {item} <= 0: does not exist".
This can be set as a condition in the normal train conditions.
And that is what LTN is setting by default.
![image](https://user-images.githubusercontent.com/41681946/44571137-e440ae80-a7ba-11e8-9e58-773d33e5e3e3.png)
And this is when you don't see an output signal.
But if you change this to 
Cargo: {item} <= 0
You can get an output signal.
![image](https://user-images.githubusercontent.com/41681946/44571248-341f7580-a7bb-11e8-8e9b-92a7cf209a8d.png)


Not sure if this is a bug or not, but I was expecting to see the arriving quantity in the output signal.

**Comment by Yousei9** [comment]
LTN catches > n, ≥ n and = 0 and correctly ouputs signals for 1 arithmetic combinator control of filter inserters.
Read the manual or look into the demo save.
