### ISSUE TITLE
Ability to read logistic train network

### ISSUE THREAD

**Issue by clrkio** [Yousei9/Logistic-Train-Network#134]
I would like to have an item which outputs everything available on the LTN, which I can attach to a circuit network. This could be used in a variety of ways - a base-wide resource monitor, turning on and off recipes, etc.

**Comment by Yousei9** [comment]
I don't see the merit in summing up provided - requested + deliveries for each item.
Turning factories on and off can be done much simpler by monitoring attached provider buffer chests.

**Comment by Yousei9** [comment]
1.9.x added a remote interface to read all data LTN uses internally from other mods.
See https://forums.factorio.com/viewtopic.php?f=214&t=62870 for usage manual.
