### ISSUE TITLE
Station able to be placed on top of existing signal

### ISSUE THREAD

**Issue by Jelmergu** [Yousei9/Logistic-Train-Network#136]
It is possible to place a LTN station on top of a rail signal.

To do so, you first place a signal next to the rail and place the station on the square above it. The output of the LTN station will be placed over the rail signal
![Placing on signal](https://user-images.githubusercontent.com/18192158/46065088-7993e180-c171-11e8-9b04-00bcc80525ba.png)
![Placing result](https://user-images.githubusercontent.com/18192158/46065125-9203fc00-c171-11e8-98d0-5409fb0da530.png)

**Comment by Yousei9** [comment]
That behavior is well known for modded entities consisting of multiple base game entities.
When placing the main entity (stop) only it's bounding box is checked by the game.
However bounding boxes of stop, output and input must not overlap or it blocks itself when blueprinting.
