### ISSUE TITLE
Request: LTN Network ID

### ISSUE THREAD

**Issue by Blackphidora** [Yousei9/Logistic-Train-Network#14]
I would like to be separate LTN network by some sort of Identifier, Mostly to allow for smaller inside base train logistic (either for one or most LTN networks) and for my longer reaching resources outside my base.

I do not know if this helps PVP scenarios.

**Comment by Yousei9** [comment]
This request comes up regularly. 
I don't see a need for splitting up the network. You can use different train sizes and min/max train length to create sub-networks.

There's no way with the current game mechanics and api to fully support PvP. Trains will always go to the nearest station of a given name regardless which force it belongs to.

**Comment by rperce** [comment]
Here's another vote for proper separate train networks. In my current save with LTN, I've just completed science, so I'm bootstrapping a larger, rocket-focused base that doesn't have to worry about it. For really high throughput, I'd like to use an internal train network in the new base. However, I'm running into problems with the train network at the old base (which is still running, building what I need to build the new base) attempting to path to stations in the new base. I'd like to include a network ID in combinator input to solve that, or, even better, have depots figure out which stations are connected to the depot by tracks, and only provide routes to possible stations (disregarding signalling issues, I'd think). I'm not sure how much extra CPU that'd take overall --- IIRC, all trains repath whenever rails are placed, so perhaps there's already a mechanic to hook into that event? 

If you prefer, I can open that feature request as a new issue.

**Comment by Yousei9** [comment]
I understand the request from a player perspective. 
It just creates so many edge cases I don't want to tackle considering the benefits are so small.

>  have depots figure out which stations are connected to the depot by tracks, and only provide routes to possible stations (disregarding signalling issues, I'd think).
Unless i get the api provides a network graph that will never happen.
Coding it myself with what the api provides would take insane amounts of work, code and cpu time. I'd have to grab every piece of track from the entire surface, analyze position and orientation and piece together the network from that.

When adding support for multiple forces I made sure LTN only works if stops and train are all in the same force.
I never tested it, but in theory you could use spacebook or console commands to create another friendly force to build stops and trains of the new network with it.
If you go for this please let me know about the results. I've never had time to test multiple factions on a large scale.

Note: Factorio faction support is very rudimentary:
Trains happily use even hostile forces tracks, signals and stops.
Inserters loading a train can be neutral or hostile, unloading inserters need to be same force (or friendly?)

**Comment by Smileynator** [comment]
Ah whelp, just requested this on the forums, but would an ID number constant combinator to take into account with each delivery planned not fix the issue easily?
Assume "no ID" means the station is neutral/fair game for whatever train. If not, you need to define a specific ID to the station, and in that case it will only mix/match with any neutral or one of the same ID. I haven't looked into the mod's code. But it doesn't sound that hard from a programmers perspective?
Am i missing anything obvious?

**Comment by mgravell** [comment]
Hi; love the mod - awesome work. I'm also interested in multiple networks without the somewhat artificial hack of using the train length. I've looked at the code, and I think I know where I'd hook it (nice clean code with useful comments, thanks). Would you be interested in a PR at all, or are you firmly of the "nope, that's not going into LTN" mindset?

**Comment by Yousei9** [comment]
If you had read my comments on this before posting you would know I don't see a point in adding multiple networks.
Not only would it defeat the purpose of having all train capacity available for any delivery,  I also don't want to deal with bug reports of players who managed to create deadlocks by having stations on different IDs.

**Comment by mgravell** [comment]
Fair enough; that's up to you as the owner. To talk about benefits, though; I'm working with a train bus, with some of the items (circuits etc) being delivered to the bus as completed products rather than being created on the main bus. Consequently, I want a *separate* network driving those products (especially since red and blue needs a full oil setup), and I actively don't want the two networks connected - they are both logically and physically separate. A network id would have been a perfect way to solve this without causing confused routing.

Oh well, I guess I can either do it in a local fork, or hack around it with train lengths.

Thanks again for the mod.

**Comment by Templarfreak** [comment]
Very, very simple solution to basically all problems with this:

Just give rails an adjustable output like Combinators, a toggle to have it output (Either on or off, on = always output off = never output) and allow it to connect to the Circuit Network, 

Boom. A player can make their own separate rail networks with basically any behavior they're willing to write themselves using Circuit Networks. You wouldn't even have to network in every single rail, either, only the ones you want to have certain behavior with.

**Comment by mgravell** [comment]
@Templarfreak  maybe I'm missing something, but I fail to see how that relates to multiple networks and LTN. The fundamental issue, as I see it, is that sometimes you have multiple physical rail infrastructures. It doesn't matter *what* you signal if LTN is going to try to solve a request by routing a supplier to a requester on different physical networks. Hence why a network ID solves the issue. You cannot currently use "separate rail networks" on LTN without changes - turning things off and on won't solve that.

**Comment by Templarfreak** [comment]
of course, you'd have to make LTN actually pay attention to this new circuit behavior, but I'm pretty confident that the existing circuit network capabilities could be used to program any behavior a person could want. All that would be needed ontop of my original post is some new LTN circuit conditions/behaviors to tell the LTN Network what to do based on what circuit conditions. Perhaps trains by default would have to be made to ignore all stops that are not within their circuit network, and what circuit network they are in would be determined by what LTN Depot is in their stop list.

**Comment by UFTimmy** [comment]
I respect you have said you won't do this, but I will give a use case where this would be useful to me.

I want to build a series of processing steps, one for each science type. So for space science, ore comes in, gets turned into steel, then goes to the left, gets turned into Low Density Structures, then goes to the left, gets turned into rockets. The same for each part, but in one long, narrow strip. Each strip will produce 1k science of that type.

The different strips will be stacked vertically on each other, so it's quite possible the steel smelter provider from a different line will be closer to the low density structures than the one that is actually connected via rails.

LTN,  I believe, picks the closest provider as the crow flies, assuming the same priority. I would prefer if I could choose the provider by setting a network id circuit condition or something similar so it would not pick the closest one, but rather the one that is actually connected via rails.

**Comment by Yousei9** [comment]
What you described sounds like a job for static schedules, with perhaps disabling stops through circuit network.
LTN always presumes a fully interconnected network where trains can reach each requester from any potential provider.

**Comment by UFTimmy** [comment]
Perhaps what I am describing does not strictly require LTN, for all of it, but I enjoy the depots, and the refueling the depots as needed.

The design I was planning would have everything interconnected, because each of the spurs would connect to the mining outposts, but it would take much longer from steel to get from one spur to another, but as the crow flies, it may be closer.

I can rig it using train lengths, but that would mean putting useless wagons or locos on the trains just to create sub networks.

Allowing a network ID circuit signal would basically be a way for me to tell LTN which providers and requester work best together, because I have more information than LTN. LTN can only see closest distance, but I can tell you fastest travel time.

**Comment by Yousei9** [comment]
I forgot to mention you have it backwards. LTN picks the closest size matched train in a depot to the "best" (priority > train count > item count) provider. Distance between stops otherwise is completely ignored.

If your lines are dedicated you can have a shared depot and only enable request and provider of a line with the same signal. 
Make sure to enable both stops at the same time, limit them to 1 train and disable each stop as soon as the control lamp switches from yellow to green (could also be done with reading the train id from the stop which is a few ticks faster than stop update for the control lamp).

**Comment by UFTimmy** [comment]
Say I have a steel requester, and it hits the threshold where it's going to make a request.

There are two stations providing steel, both have the same train min/max, and both have exactly the item amount requested, no less, no more. What is the factor that determines which one gets picked?

**Comment by Yousei9** [comment]
Whichever happens to be first in the array.

**Comment by UFTimmy** [comment]
Thanks.

But depot trains are picked by proximity to the providing station, correct?

**Comment by Yousei9** [comment]
Not as top priority but yes.
It checks for the smallest possible if any train is bigger than the request or largest available if the request exceeds all train capacities first.

**Comment by dgoeke** [comment]
Would it be possible to set a signal at the depot stop, `network = 3` and then at the outpost, `network = 3`?  Then when filling requests, just don't choose trains at depots that don't match.  Factorio's pathfinding can handle the rest.  For megabases, separate networks are a major win.

**Comment by mgravell** [comment]
@dgoeke there was a PR that added exactly that, which worked fine - but the
author chose not to merge it (as is their right) - they don't like that
idea.

**Comment by Yousei9** [comment]
Added to version 1.7.0.
