### ISSUE TITLE
Feature-Request: Option to set minimum transport amount on requester-station

### ISSUE THREAD

**Issue by ekle** [Yousei9/Logistic-Train-Network#142]
This would allow to not set any amount restrictions on a provider and instead set them on the requester.

At the moment i have the problem that small amounts which are requested, while a requester storage gets empty, choose a provider, which does have everything(in a small amount) to support outposts.

at the moment i solve this by using different train sizes, but this has the disadvantage, that i need two providers for every item with different Provide Threshold.

**Comment by Yousei9** [comment]
Transported amount depends on request and provide threshold.
see the graphic here: https://forums.factorio.com/viewtopic.php?f=214&t=51072

Delivery size will be either provide threshold, request threshold or train size whichever is smallest.

**Comment by Yousei9** [comment]
I see no benefit in sending 10 items per train. Trains are best utilized when they only run for full loads.

But it you want to have empty trains running around, limiting by request threshold generally works much better.

**Comment by ekle** [comment]
the small number where just for the example
you can add a few zero to the numbers, the problem is the same.

if you have requesters with very different request size, you don't want a train with a small amount, which is fine for a small requester, go to the big requester. 
The only way to archive this at the moment is to have two providers.

a solution to this could be, to set the "Provide Threshold" on a requester-station.

**Comment by Yousei9** [comment]
LTN will always pick the smallest possible train that can fit the entire delivery.
You can force certain trains to stations using train length or network id.
