### ISSUE TITLE
Noxy's Multidirectional Trains Dependency

### ISSUE THREAD

**Issue by MaddMugsy** [Yousei9/Logistic-Train-Network#151]
The version of the optional dependency on Noxy's Multidirectional trains is >=0.1.0, but the latest version of that mod is 0.0.7.

**Comment by Yousei9** [comment]
Yes, when Noxy accepts the pull request he'll be at 0.1.0 and compatible with LTN.

**Comment by CyaNox** [comment]
You may still have to adjust your dependency ... but then again I don't think you need the optional dependency at all since the load order of these two mods are irrelevant.

**Comment by MaddMugsy** [comment]
This dependency is currently disabling LTN, so it probably needs to be updated or removed.

**Comment by Yousei9** [comment]
The main reason for having the dependency was to signal that LTN is compatible to the reworked MDT while simultaneously showing users their 0.7.0 version is not.
I have to test if dependency matters which mod receives events first.

If your implementation behaves like my proposed changes I'll lower the dependency version to 0.8.0.

**Comment by CyaNox** [comment]
You could maybe add a incompatibility in the dependencies like:
```
"! Noxys_Multidirectional_Trains <= 0.0.7"
```
But I've not tried this yet so I don't know how well that would work.

**Comment by Yousei9** [comment]
Theoretically, but I wont release another version just for that.
I've listed MDT as compatible 0.0.8 and upwards in the manual. If users run outdated mod versions it's their own fault.

**Comment by CyaNox** [comment]
Agreed
