### ISSUE TITLE
Mod settings reset randomly

### ISSUE THREAD

**Issue by CmdrVoid** [Yousei9/Logistic-Train-Network#156]
Hi

with the new version the option "Schedule circuit conditions" is active even if turned off.

Cheers!
CmdrVoid

**Comment by Yousei9** [comment]
I keep hearing about settings toggling themself.
All my settings are treated as read only and I was unable to reproduce it myself. 

My guess would be that it is a bug with recent API changes allowing mods to change settings.

**Comment by Yousei9** [comment]
This seems to have been fixed.
