### ISSUE TITLE
Error When removing a train

### ISSUE THREAD

**Issue by sebbi08** [Yousei9/Logistic-Train-Network#168]
**Error message or bug description**
The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_pre_player_mined_item (ID 11)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 202)
__LTN_Tracker__/ltnt/data_processing.lua:493: attempt to call upvalue 'get_main_loco' (a nil value)
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:493: in function <__LTN_Tracker__/ltnt/data_processing.lua:486>
stack traceback:
	__LogisticTrainNetwork__/script/stop-events.lua:262: in function <__LogisticTrainNetwork__/script/stop-events.lua:249>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/stop-events.lua:262: in function <__LogisticTrainNetwork__/script/stop-events.lua:249>

**To Reproduce**
I am using https://mods.factorio.com/mod/TheBlueprintLab_bud to build some Station Blue prints sadly because of this https://github.com/Yousei9/Logistic-Train-Network/issues/163 the depos mixed with my "normal" network. So one of the Lab Trains got scheduled to make a normal deliver but there was no path obviusly. The error occured when i tried to remove the Train.

**LTN version**
1.10.5

**Log file**
   0.001 2019-04-02 19:21:23; Factorio 0.17.23 (build 44171, win64, steam)
   0.002 Operating system: Windows 10 (version 1709) 
   0.003 Program arguments: "C:\Spiele\Steam Games\steamapps\common\Factorio\bin\x64\Factorio.exe" 
   0.003 Read data path: C:/Spiele/Steam Games/steamapps/common/Factorio/data
   0.003 Write data path: C:/Users/Sebastian/AppData/Roaming/Factorio [19189/475502MB]
   0.003 Binaries path: C:/Spiele/Steam Games/steamapps/common/Factorio/bin
   0.013 System info: [CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, 4 cores, RAM: 6945/16237 MB, page: 11673/21170 MB, virtual: 231/134217727 MB, extended virtual: 0 MB]
   0.014 Display options: [FullScreen: 0] [VSync: 1] [UIScale: automatic (100.0%)] [Native DPI: 1] [Screen: 255] [Special: 00] [Lang: en]
   0.033 Available displays: 3
   0.033  [0]: \\.\DISPLAY1 - AMD Radeon (TM) R9 390 Series {0x80005, [0,0], 1920x1080, 32bit, 59Hz}
   0.034  [1]: \\.\DISPLAY2 - AMD Radeon (TM) R9 390 Series {0x80001, [1920,0], 1280x1024, 32bit, 60Hz}
   0.035  [2]: \\.\DISPLAY3 - AMD Radeon (TM) R9 390 Series {0x80001, [3200,0], 1920x1080, 32bit, 59Hz}
   0.079 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
   0.166 Initialised Direct3D[0]: AMD Radeon (TM) R9 390 Series; id: 1002-67b1; driver: aticfx64.dll 25.20.15011.1004
   0.166   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 1,discard,-,-,none
   0.166   [Local Video Memory] Budget: 6943MB, CurrentUsage: 0MB, Reservation: 0/3675MB
   0.166   [Non-Local Vid.Mem.] Budget: 7307MB, CurrentUsage: 0MB, Reservation: 0/3856MB
   0.166   Tiled resources: Tier 2
   0.166   Unified Memory Architecture: No
   0.166   BGR 565 Supported: Yes
   0.167   MaximumFrameLatency: 3, GPUThreadPriority: 0
   0.209 Desktop composition is active.
   0.210 Graphics settings preset: very-high
   0.210   Dedicated video memory size 8168 MB
   0.210 Graphics options: [Graphics quality: high] [Video memory usage: all] [Light scale: 100%] [DXT: none]
   0.210                   [Max load threads: 32] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: normal] [Color: 32bit]
   0.258 DSound: Starting _dsound_update thread
   0.258 DSound: Enter _dsound_update; tid=4700
   0.493 Loading mod settings additional-paste-settings-17 0.0.1 (settings.lua)
   0.558 Loading mod settings auto-research 5.0.1 (settings.lua)
   0.564 Loading mod settings AutoDeconstruct 0.1.12 (settings.lua)
   0.564 Loading mod settings AutomaticLogisticChest 0.7005.33974 (settings.lua)
   0.565 Loading mod settings Automatic_Train_Painter 0.2.8 (settings.lua)
   0.566 Loading mod settings bobenemies 0.17.2 (settings.lua)
   0.566 Loading mod settings bobinserters 0.17.3 (settings.lua)
   0.566 Loading mod settings Bottleneck 0.10.3 (settings.lua)
   0.567 Loading mod settings Fill4Me 0.5.4 (settings.lua)
   0.567 Loading mod settings Flare Stack 2.2.3 (settings.lua)
   0.568 Loading mod settings helmod 0.8.7 (settings.lua)
   0.568 Loading mod settings LogisticRequestHinter 1.1.0 (settings.lua)
   0.569 Loading mod settings quick-start 1.1.3 (settings.lua)
   0.570 Loading mod settings RPGsystem 0.17.22 (settings.lua)
   0.571 Loading mod settings Shortcuts 0.6.0 (settings.lua)
   0.572 Loading mod settings YARM 0.8.4 (settings.lua)
   0.572 Loading mod settings bobores 0.17.1 (settings.lua)
   0.573 Loading mod settings bobtech 0.17.2 (settings.lua)
   0.573 Loading mod settings bobvehicleequipment 0.17.0 (settings.lua)
   0.574 Loading mod settings LogisticTrainNetwork 1.10.5 (settings.lua)
   0.575 Loading mod settings bobplates 0.17.2 (settings.lua)
   0.576 Loading mod settings LTN_Tracker 0.9.8 (settings.lua)
   0.577 Loading mod settings rso-mod 4.0.3 (settings.lua)
   0.578 Loading mod settings bobassembly 0.17.2 (settings.lua)
   0.578 Loading mod settings bobelectronics 0.17.2 (settings.lua)
   0.579 Loading mod settings boblogistics 0.17.6 (settings.lua)
   0.580 Loading mod settings bobmining 0.17.2 (settings.lua)
   0.580 Loading mod settings bobpower 0.17.3 (settings.lua)
   0.581 Loading mod settings bobwarfare 0.17.3 (settings.lua)
   0.582 Loading mod settings bobmodules 0.17.2 (settings.lua)
   0.582 Loading mod settings LoaderRedux 1.4.8 (settings.lua)
   0.583 Loading mod settings BlueprintExtensions 0.4.3 (settings.lua)
   0.584 Loading mod settings reverse-factory 6.0.4 (settings.lua)
   0.591 Loading mod core 0.0.0 (data.lua)
   0.660 Loading mod base 0.17.23 (data.lua)
   0.926 Loading mod WireShortcuts 0.2.177 (data.lua)
   1.015 Loading mod additional-paste-settings-17 0.0.1 (data.lua)
   1.145 Loading mod auto-research 5.0.1 (data.lua)
   1.290 Loading mod BlueprintLab_Bud17 0.17.0 (data.lua)
   1.396 Loading mod bobenemies 0.17.2 (data.lua)
   1.509 Loading mod bobinserters 0.17.3 (data.lua)
   1.612 Loading mod boblibrary 0.17.0 (data.lua)
   1.735 Loading mod BotRecaller 0.17.3 (data.lua)
   1.830 Loading mod Bottleneck 0.10.3 (data.lua)
   1.937 Loading mod Empty_Miner_Tool 0.3.0 (data.lua)
   2.038 Loading mod epic_mining_and_crafting_speed_research 5.2.0 (data.lua)
   2.132 Loading mod Flare Stack 2.2.3 (data.lua)
   2.225 Loading mod Flow Control 3.0.4 (data.lua)
   2.317 Loading mod FNEI 0.2.3 (data.lua)
   2.416 Loading mod GlobalConstantCombinator 0.17.0 (data.lua)
   2.509 Loading mod helmod 0.8.7 (data.lua)
   2.612 Loading mod LogisticRequestHinter 1.1.0 (data.lua)
   2.720 Loading mod OpteraLib 0.1.2 (data.lua)
   2.832 Loading mod RPGsystem 0.17.22 (data.lua)
   2.926 Loading mod Vehicle_Radar 0.5.1 (data.lua)
   3.020 Loading mod WaterWell 1.0.20 (data.lua)
   3.112 Loading mod YARM 0.8.4 (data.lua)
   3.204 Loading mod bobclasses 0.17.3 (data.lua)
   3.292 Loading mod bobores 0.17.1 (data.lua)
   3.396 Loading mod bobtech 0.17.2 (data.lua)
   3.482 Loading mod bobvehicleequipment 0.17.0 (data.lua)
   3.589 Loading mod LogisticTrainNetwork 1.10.5 (data.lua)
   3.679 Loading mod OutpostPlanner 1.1.1 (data.lua)
   3.781 Loading mod bobplates 0.17.2 (data.lua)
   3.884 Loading mod LTN_Tracker 0.9.8 (data.lua)
   3.978 Loading mod rso-mod 4.0.3 (data.lua)
   4.080 Loading mod bobassembly 0.17.2 (data.lua)
   4.185 Loading mod bobelectronics 0.17.2 (data.lua)
   4.285 Loading mod bobgreenhouse 0.17.0 (data.lua)
   4.383 Loading mod boblogistics 0.17.6 (data.lua)
   4.507 Loading mod bobmining 0.17.2 (data.lua)
   4.616 Loading mod bobpower 0.17.3 (data.lua)
   4.746 Loading mod bobrevamp 0.17.1 (data.lua)
   4.871 Loading mod bobwarfare 0.17.3 (data.lua)
   5.005 Loading mod bobmodules 0.17.2 (data.lua)
   5.130 Loading mod LoaderRedux 1.4.8 (data.lua)
   5.254 Loading mod BlueprintExtensions 0.4.3 (data.lua)
   5.375 Loading mod reverse-factory 6.0.4 (data.lua)
   5.506 Loading mod base 0.17.23 (data-updates.lua)
   5.628 Loading mod bobenemies 0.17.2 (data-updates.lua)
   5.753 Loading mod bobinserters 0.17.3 (data-updates.lua)
   5.885 Loading mod NoEmptyBarrels 0.0.3 (data-updates.lua)
   6.028 Loading mod Shortcuts 0.6.0 (data-updates.lua)
   6.163 Loading mod Squeak Through 1.3.0 (data-updates.lua)
   6.295 Loading mod bobclasses 0.17.3 (data-updates.lua)
   6.422 Loading mod bobores 0.17.1 (data-updates.lua)
   6.553 Loading mod bobtech 0.17.2 (data-updates.lua)
   6.705 Loading mod bobvehicleequipment 0.17.0 (data-updates.lua)
   6.848 Loading mod bobplates 0.17.2 (data-updates.lua)
   6.850 Script @__boblibrary__/module-functions.lua:12: Recipe polishing-wheel-synthetic does not exist.
   7.010 Loading mod bobassembly 0.17.2 (data-updates.lua)
   7.149 Loading mod bobelectronics 0.17.2 (data-updates.lua)
   7.284 Loading mod bobgreenhouse 0.17.0 (data-updates.lua)
   7.454 Loading mod boblogistics 0.17.6 (data-updates.lua)
   7.456 Script @__boblibrary__/recipe-functions.lua:76: Recipe bob-roboport-2 does not exist.
   7.457 Script @__boblibrary__/recipe-functions.lua:76: Recipe bob-roboport-3 does not exist.
   7.457 Script @__boblibrary__/recipe-functions.lua:76: Recipe bob-roboport-4 does not exist.
   7.462 Script @__boblibrary__/technology-functions.lua:131: Technology character-inventory-slots-3 does not exist.
   7.606 Loading mod bobmining 0.17.2 (data-updates.lua)
   7.761 Loading mod bobpower 0.17.3 (data-updates.lua)
   7.908 Loading mod bobrevamp 0.17.1 (data-updates.lua)
   8.079 Loading mod bobwarfare 0.17.3 (data-updates.lua)
   8.081 Script @__boblibrary__/recipe-functions.lua:76: Recipe gun-cotton-synthetic does not exist.
   8.085 Script @__boblibrary__/module-functions.lua:12: Recipe gun-cotton-synthetic does not exist.
   8.220 Loading mod bobmodules 0.17.2 (data-updates.lua)
   8.357 Loading mod LoaderRedux 1.4.8 (data-updates.lua)
   8.493 Loading mod reverse-factory 6.0.4 (data-updates.lua)
   8.631 Loading mod WireShortcuts 0.2.177 (data-final-fixes.lua)
   8.767 Loading mod auto-research 5.0.1 (data-final-fixes.lua)
   8.903 Loading mod Flare Stack 2.2.3 (data-final-fixes.lua)
   9.048 Loading mod walls-block-spitters 0.4.3 (data-final-fixes.lua)
   9.213 Loading mod LogisticTrainNetwork 1.10.5 (data-final-fixes.lua)
   9.215 Script @__LogisticTrainNetwork__/data-final-fixes.lua:84: [LTN] found 993 items, 34 fluids, 5 locomotives, 16 wagons
   9.367 Loading mod bobplates 0.17.2 (data-final-fixes.lua)
   9.508 Loading mod rso-mod 4.0.3 (data-final-fixes.lua)
   9.640 Loading mod bobelectronics 0.17.2 (data-final-fixes.lua)
   9.810 Loading mod GDIW 0.17.4 (data-final-fixes.lua)
   9.950 Loading mod reverse-factory 6.0.4 (data-final-fixes.lua)
   9.961 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: power-armor-mk2
   9.961 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: fusion-reactor-equipment
   9.962 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: personal-roboport-mk2-equipment
   9.962 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: rocket-silo
   9.962 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: satellite
   9.963 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: nuclear-reactor
   9.963 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: vehicle-fusion-reactor-1
   9.968 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: artillery-wagon
   9.968 Script @__reverse-factory__/add-recipes.lua:476: Item cannot be uncrafted: tank
  10.126 Checksum for core: 1532611835
  10.137 Checksum of base: 3383128201
  10.169 Checksum of WireShortcuts: 3283877692
  10.171 Checksum of additional-paste-settings-17: 903829378
  10.171 Checksum of auto-research: 2958201390
  10.171 Checksum of AutoDeconstruct: 2582707891
  10.172 Checksum of AutomaticLogisticChest: 755511088
  10.172 Checksum of Automatic_Train_Painter: 3487700803
  10.172 Checksum of BlueprintLab_Bud17: 2980325627
  10.172 Checksum of bobenemies: 2278274707
  10.173 Checksum of bobinserters: 985220932
  10.173 Checksum of boblibrary: 1591833824
  10.173 Checksum of BotRecaller: 1290637299
  10.174 Checksum of Bottleneck: 3138809866
  10.174 Checksum of ChangeMapSettings: 0
  10.174 Checksum of Empty_Miner_Tool: 3146116233
  10.174 Checksum of epic_mining_and_crafting_speed_research: 2467236023
  10.175 Checksum of Fill4Me: 4262085054
  10.176 Checksum of Flare Stack: 2374449
  10.178 Checksum of Flow Control: 3821924777
  10.180 Checksum of FNEI: 3393476267
  10.181 Checksum of GlobalConstantCombinator: 1494606593
  10.181 Checksum of helmod: 111155820
  10.182 Checksum of LogisticRequestHinter: 3366494625
  10.182 Checksum of NoEmptyBarrels: 3914992378
  10.182 Checksum of OpteraLib: 1315444285
  10.183 Checksum of PlannerCore: 0
  10.183 Checksum of quick-start: 1636235082
  10.183 Checksum of RPGsystem: 2249764363
  10.184 Checksum of Shortcuts: 1269156604
  10.184 Checksum of Squeak Through: 3677677690
  10.184 Checksum of Vehicle_Radar: 3453163269
  10.184 Checksum of walls-block-spitters: 415044876
  10.185 Checksum of WaterWell: 4254977431
  10.185 Checksum of YARM: 811007728
  10.185 Checksum of bobclasses: 3836832883
  10.186 Checksum of bobores: 3626124899
  10.186 Checksum of bobtech: 4164274838
  10.186 Checksum of bobvehicleequipment: 2728567119
  10.186 Checksum of LogisticTrainNetwork: 2418824010
  10.187 Checksum of OutpostPlanner: 1664633010
  10.187 Checksum of bobplates: 4004719936
  10.187 Checksum of LTN_Tracker: 3584344671
  10.188 Checksum of rso-mod: 83009251
  10.188 Checksum of bobassembly: 24878518
  10.188 Checksum of bobelectronics: 1833912833
  10.188 Checksum of bobgreenhouse: 2485507801
  10.190 Checksum of boblogistics: 614906478
  10.190 Checksum of bobmining: 1214531256
  10.191 Checksum of bobpower: 2184262608
  10.191 Checksum of bobrevamp: 2595430217
  10.191 Checksum of bobwarfare: 1644495301
  10.192 Checksum of bobmodules: 20345667
  10.192 Checksum of GDIW: 3345880964
  10.192 Checksum of LoaderRedux: 2063638280
  10.192 Checksum of BlueprintExtensions: 708079482
  10.193 Checksum of reverse-factory: 3804502875
  10.582 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 0.008) as emissions will be not used soon: ROOT.furnace.flare-stack.energy_source
  10.583 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 5e-05) as emissions will be not used soon: ROOT.furnace.incinerator.energy_source
  10.584 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 5e-05) as emissions will be not used soon: ROOT.furnace.electric-incinerator.energy_source
  10.585 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 0.008) as emissions will be not used soon: ROOT.furnace.vent-stack.energy_source
  10.585 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 5e-06) as emissions will be not used soon: ROOT.furnace.reverse-factory-1.energy_source
  10.586 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 5e-06) as emissions will be not used soon: ROOT.furnace.reverse-factory-2.energy_source
  10.602 Warning EnergySourcePrototype.cpp:81: emissions in prototype definition, use emissions_per_second_per_watt (proposed value 0.0001) as emissions will be not used soon: ROOT.assembling-machine.water-well-pump.energy_source
  10.931 Loading sounds...
  11.307 Info PlayerData.cpp:69: Local player-data.json unavailable
  11.308 Info PlayerData.cpp:72: Cloud player-data.json available, timestamp 1554057566
  11.503 Initial atlas bitmap size is 16384
  11.531 Created atlas bitmap 16384x16382 [not-compressed]
  11.535 Created atlas bitmap 16384x10046 [not-compressed]
  11.535 Created atlas bitmap 16384x2107 [decal, not-compressed]
  11.537 Created atlas bitmap 16384x8424 [low-object, not-compressed]
  11.538 Created atlas bitmap 16384x2412 [not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level, no-crop, no-scale]
  11.539 Created atlas bitmap 16384x6880 [terrain, not-compressed, mipmap, linear-minification, linear-mip-level, no-crop]
  11.540 Created atlas bitmap 16384x476 [smoke, not-compressed, mipmap, linear-minification, linear-magnification]
  11.541 Created atlas bitmap 16384x748 [alpha-mask]
  11.543 Created atlas bitmap 16384x12636 [shadow, linear-magnification, alpha-mask]
  11.543 Created atlas bitmap 16384x1264 [shadow, mipmap, linear-magnification, alpha-mask]
  11.552 Texture processor created. GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  22.260 Parallel Sprite Loader initialized (threads: 3)
  35.098 Sprites loaded
  35.190 Generated mipmaps for atlas of size 16384x8424
  35.201 Generated mipmaps for atlas of size 16384x2412
  35.221 Generated mipmaps for atlas of size 16384x6880
  35.232 Generated mipmaps for atlas of size 16384x476
  35.242 Generated mipmaps for atlas of size 16384x1264
  35.254 Custom inputs active: 55
  35.336 Factorio initialised
  59.613 Info HttpSharedState.cpp:54: Downloading https://mods.factorio.com/api/mods?page_size=max&namelist=additional-paste-settings-17&namelist=auto-research&namelist=AutoDeconstruct&namelist=AutomaticLogisticChest&namelist=Automatic_Train_Painter&namelist=BlueprintExtensions&namelist=BlueprintLab_Bud17&namelist=bobassembly&namelist=bobclasses&namelist=bobelectronics&namelist=bobenemies&namelist=bobgreenhouse&namelist=bobinserters&namelist=boblibrary&namelist=boblogistics&namelist=bobmining&namelist=bobmodules&namelist=bobores&namelist=bobplates&namelist=bobpower&namelist=bobrevamp&namelist=bobtech&namelist=bobvehicleequipment&namelist=bobwarfare&namelist=BotRecaller&namelist=Bottleneck&namelist=ChangeMapSettings&namelist=Empty_Miner_Tool&namelist=epic_mining_and_crafting_speed_research&namelist=Fill4Me&namelist=Flare%20Stack&namelist=Flow%20Control&namelist=FNEI&namelist=GDIW&namelist=GlobalConstantCombinator&namelist=helmod&namelist=LoaderRedux&namelist=LogisticRequestHinter&namelist=LogisticTrainNetwork&namelist=LTN_Tracker&namelist=NoEmptyBarrels&namelist=OpteraLib&namelist=OutpostPlanner&namelist=PlannerCore&namelist=quick-start&namelist=reverse-factory&namelist=RPGsystem&namelist=rso-mod&namelist=Shortcuts&namelist=Squeak%20Through&namelist=Vehicle_Radar&namelist=walls-block-spitters&namelist=WaterWell&namelist=WireShortcuts&namelist=YAR
  63.137 Info HttpSharedState.cpp:54: Downloading https://mods.factorio.com/api/categories
  63.137 Info HttpSharedState.cpp:54: Downloading https://mods.factorio.com/api/mods?page_size=max&version=0.17
  67.455 Loading map D:\ModMyFactory_1.9.0_portable\saves\_autosave1.zip: 8639856 bytes.
  67.511 Loading level.dat: 28830437 bytes.
  67.516 Info Scenario.cpp:161: Map version 0.17.23-1
  68.577 Loading script.dat: 533589 bytes.
  68.584 Checksum for script C:/Users/Sebastian/AppData/Roaming/Factorio/temp/currently-playing/control.lua: 1848333929
  68.585 Checksum for script __WireShortcuts__/control.lua: 3490489245
  68.586 Checksum for script __additional-paste-settings-17__/control.lua: 3738120640
  68.588 Checksum for script __auto-research__/control.lua: 2436068303
  68.591 Checksum for script __AutoDeconstruct__/control.lua: 2848553575
  68.592 Checksum for script __AutomaticLogisticChest__/control.lua: 931099559
  68.598 Checksum for script __Automatic_Train_Painter__/control.lua: 1030518902
  68.600 Checksum for script __BlueprintLab_Bud17__/control.lua: 2399618123
  68.603 Checksum for script __bobinserters__/control.lua: 2636244137
  68.603 Checksum for script __BotRecaller__/control.lua: 475872183
  68.605 Checksum for script __Bottleneck__/control.lua: 1724301457
  68.608 Checksum for script __ChangeMapSettings__/control.lua: 3301488419
  68.608 Checksum for script __Empty_Miner_Tool__/control.lua: 29032698
  68.614 Checksum for script __Fill4Me__/control.lua: 956106630
  68.615 Checksum for script __Flow Control__/control.lua: 894715649
  68.625 Checksum for script __FNEI__/control.lua: 2036981011
  68.626 Checksum for script __GlobalConstantCombinator__/control.lua: 644288045
  68.657 Checksum for script __helmod__/control.lua: 3567955364
  68.658 Checksum for script __LogisticRequestHinter__/control.lua: 992686703
  68.663 Checksum for script __PlannerCore__/control.lua: 788236622
  68.664 Checksum for script __quick-start__/control.lua: 920146629
  68.667 Checksum for script __RPGsystem__/control.lua: 3007372646
  68.669 Checksum for script __Shortcuts__/control.lua: 240864779
  68.670 Checksum for script __Vehicle_Radar__/control.lua: 3865655671
  68.671 Checksum for script __WaterWell__/control.lua: 107213243
  68.675 Checksum for script __YARM__/control.lua: 2649971922
  68.676 Checksum for script __bobclasses__/control.lua: 2451542404
  68.677 Checksum for script __bobores__/control.lua: 3649119228
  68.682 Checksum for script __LogisticTrainNetwork__/control.lua: 459846767
  68.686 Checksum for script __OutpostPlanner__/control.lua: 2472572350
  68.687 Checksum for script __bobplates__/control.lua: 2137047030
  68.694 Checksum for script __LTN_Tracker__/control.lua: 3245070014
  68.705 Checksum for script __rso-mod__/control.lua: 671899051
  68.707 Checksum for script __boblogistics__/control.lua: 3110647072
  68.708 Checksum for script __GDIW__/control.lua: 2648178700
  68.709 Checksum for script __LoaderRedux__/control.lua: 2020915148
  68.713 Checksum for script __BlueprintExtensions__/control.lua: 3146922426
  68.715 Checksum for script __reverse-factory__/control.lua: 3366288793
  68.980 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/Player.lua:222: attempt to index upvalue 'Lua_player' (a nil value)
 114.020 Error MainLoop.cpp:1142: Exception at tick 6509250: The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_pre_player_mined_item (ID 11)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 202)
__LTN_Tracker__/ltnt/data_processing.lua:493: attempt to call upvalue 'get_main_loco' (a nil value)
stack traceback:
	__LTN_Tracker__/ltnt/data_processing.lua:493: in function <__LTN_Tracker__/ltnt/data_processing.lua:486>
stack traceback:
	__LogisticTrainNetwork__/script/stop-events.lua:262: in function <__LogisticTrainNetwork__/script/stop-events.lua:249>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/stop-events.lua:262: in function <__LogisticTrainNetwork__/script/stop-events.lua:249
 371.348 Quitting: user-quit.
 371.546 DSound: Stopping voice
 371.546 DSound: Joining thread
 371.549 DSound: Exit _dsound_update; tid=4700
 371.549 DSound: Waiting for voice to stop ... signaled
 371.550 DSound: Joined thread
 371.550 DSound: Destroying thread
 371.550 DSound: Thread destroyed
 371.551 DSound: Releasing buffer
 371.551 DSound: Voice stopped
 371.551 DSound: Deallocating voice
 371.552 DSound: Deallocated voice
 371.576 Steam API shutdown.
 371.579 Goodbye

**Comment by Yousei9** [comment]
Error while running event LTN_Tracker::Custom event (ID 202)
The bug stems from LTN Tracker. Probably Eduran used his changes to my library which i reverted today.
