### ISSUE TITLE
LTN Stop Time set to 0

### ISSUE THREAD

**Issue by jmurrayufo** [Yousei9/Logistic-Train-Network#178]
**Error message or bug description**  

When `Stop timeout (ticks)` is set to any value other than `0`, the wait time at the station is zero to `0` seconds. Functional meaning the train arrives and departs before anything can happen. 

![2019-05-28 11_07_35 - Factorio 0 17 43](https://user-images.githubusercontent.com/442011/58498077-815db880-813a-11e9-86d1-11bdb95cc869.jpg)

![2019-05-28 11_09_56 - Factorio 0 17 43](https://user-images.githubusercontent.com/442011/58498084-83c01280-813a-11e9-9002-feb824a1ec97.jpg)

**To Reproduce**  
1. Create Simple Network
2. Adjust `Stop timeout (ticks)` to any non zero number. 
3. Cry as trains arrive and depart without loading/unloading cargo. 

**LTN version**  
1.10.10
LTN Tracker: 0.10.8
Optera's Liobrary: 0.1.7
![2019-05-28 11_10_16 - Factorio 0 17 43](https://user-images.githubusercontent.com/442011/58498140-a8b48580-813a-11e9-84f1-66ec3385c79a.jpg)

**Factorio Version**
0.17.43

**Log file**  
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/3228888/factorio-current.log)

**Bonus Save File**
[DEMO.zip](https://github.com/Yousei9/Logistic-Train-Network/files/3228889/DEMO.zip)
Note: Using Creative mod 1.1.4 to debug faster.

**Comment by jmurrayufo** [comment]
Further playing around has shown my reproduction steps to be bad, I'm having trouble getting it to trigger again. Will update if I can reproduce.

**Comment by Yousei9** [comment]
Thanks for the report.
Stop timeout contained a bug where changes would only apply after saving and reloading.

This bug had been sleeping there for 3 months without anyone noticing.
