### ISSUE TITLE
Setting to allow providers not to fill cars completely

### ISSUE THREAD

**Issue by alercah** [Yousei9/Logistic-Train-Network#180]
In #7 and #11, you mentioned that one of the solutions to inserters having unwanted items was to wait for programmable stack size in Factorio 0.15. But there are two issues with trying to use this to prevent inserters from holding extra unwanted items. The first is that the signal for stack size must be on a fixed signal, so without extremely complicated circuit logic (likely using a max combinator?) you can't easily pick the correct signal to send stack size. The second is that the stack size will get sent to every inserter, so again complicated circuit logic would be required to distribute the last few items correctly across inserters.

You mentioned that one solution would be leaving a small amount of the car empty. This would be my preferred approach. Could that be added as a programmable signal so that the provider can specify that it leaves a given number of items of space (you don't need whole stacks!) when doing calculations for the output port and the train schedule? That would allow these leftover items to be avoided.

**Comment by Yousei9** [comment]
That's already in LTN for more than a year.
Use locked slots control signal and the smart station designs from the design thread.

**Comment by alercah** [comment]
Ah, thanks! I completely misunderstood what "locked slots" is, then; I
thought it meant that it would lock slots *to* the desired resource rather
than locking them out.

**Comment by Yousei9** [comment]
Locked slots makes LTN not see the set number of slots when checking train capacity and therefore generating delivery sizes that allow overloading.
