### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by burninghey** [Yousei9/Logistic-Train-Network#182]
I'm playing Factorio in german. There is an issue with the available signals in constant combinators.

This is wrong, the correct german translation is: "Mindestmenge für Anforderung"
![20190705103044_1](https://user-images.githubusercontent.com/29624928/60709537-f75ef780-9f10-11e9-9121-bead3285d1b9.jpg)

This is missing, the correct german translation is: "Minimum Stapel für Anforderung", like at the other one above. Maybe just glitched a line? 
![20190705103048_1](https://user-images.githubusercontent.com/29624928/60709546-fded6f00-9f10-11e9-8c16-5204522f1a69.jpg)

Ah, and while you are there editing the file already, "Encoded positions of" in german: "Kodierte Position von"
![20190705104232_1](https://user-images.githubusercontent.com/29624928/60709978-ebc00080-9f11-11e9-9cb2-eae5ec2813d5.jpg)

Thank you! This one was confusing me for some time, until i figured out it could be a bug.. :)

**Comment by Yousei9** [comment]
Thanks for the report.
I'll fix it for the next release.

I'm not playing in German even though it's my native language. 
Technical terminology sounds cumbersome or really dumb in German. We are the morons calling a smart/mobile phone "Handy" instead of Mobiltelefon.
