### ISSUE TITLE
Multisurface support

### ISSUE THREAD

**Issue by TehFreek** [Yousei9/Logistic-Train-Network#184]
[Space Exploration](https://mods.factorio.com/mod/space-exploration) works by creating a new surface for each planet, moon, orbit, etc. This causes two issues in LTN:

1. LTN stations with the same name but on different surfaces cause name conflicts even though there is no way to reach any but one of them.

2. Trains are dispatched to a providing or requesting station even if it is unreachable from its current surface.

The first can be worked around by attaching a surface identifier when naming the station. The second can be worked around by setting the network ID, limiting you to a maximum of 32 surfaces that LTN can be used on. That limit will probably only be reached in very large games, but it is there regardless.

I propose two changes in LTN:

1. Use the (name, surface) pair to identify stations instead of just the name.

2. Only dispatch trains to the same surface they are already on.

This will also improve compatibility with the Blueprint Lab mods [\[1\]](https://mods.factorio.com/mod/BlueprintLab_Bud17) [\[2\]](https://mods.factorio.com/mod/BlueprintLab_Credomane), where having a station inside the lab will conflict with stations outside the lab.

This won't solve issues with [Factorissimo](https://mods.factorio.com/mod/Factorissimo2), which reuses a surface for multiple subfactories, but the subfactories aren't really large enough to warrant using LTN stations regardless.

**Comment by Yousei9** [comment]
Network ID was added to support diconnected rail networks, be it on the same or different surfaces.
I don't see multi surface support as a pressing matter.

**Comment by Yousei9** [comment]
Surface checks have been added in 1.11.1.
I forgot to add a tag referencing this issue in that release.
