### ISSUE TITLE
You don't handle pre surface cleared/pre surface deleted

### ISSUE THREAD

**Issue by Bilka2** [Yousei9/Logistic-Train-Network#186]
Following this issue, you subscribed to the NewGamePlus custom pre surface cleared event in 0.16: https://github.com/Yousei9/Logistic-Train-Network/issues/139, https://github.com/Yousei9/Logistic-Train-Network/blob/master/script/init.lua#L227 (thank you for that)

However, with 0.17 the game calls on pre surface cleared automatically, so I removed my custom event. It looks like you are not handling the new base-game event at all, see https://mods.factorio.com/mod/NewGamePlus/discussion/5d3e289cc7cf45000c4fea89

So, just change the line I linked above to subscribe to https://lua-api.factorio.com/latest/events.html#on_pre_surface_deleted and https://lua-api.factorio.com/latest/events.html#on_pre_surface_cleared instead and that should solve all issues. Thank you!

**Comment by Yousei9** [comment]
Thanks for the reminder, I stopped following api updates closely.

Will be changed for next release.
