### ISSUE TITLE
Encoded locomotive position not reporting with mod locomotives

### ISSUE THREAD

**Issue by JonAdamsFromNC** [Yousei9/Logistic-Train-Network#191]
I'm currently using a laundry list of mod's, but while trying to use Bob's Locomotive, ex Locomotive Mk2, the encoded position of locomotive is not being reported.  As soon as the locomotive is replaced with the "Locomotive", the position is immediately reported correctly.

**To Reproduce**  
Send Locomotive Mk2 to LTN station, view "Encoded Positions of Locomotive" circuit network signal

**LTN version**  
1.10.11

**Log file**  
n/a

**Comment by JonAdamsFromNC** [comment]
I've now figured out that the "Encoded Positions" signals are per wagon / locomotive type.
Would it be possible / reasonable / logical to add a one signal for "Cargo Wagon" and "Locomotive" regardless of type? Or is it intentionally necessary to require separate depots in this way?

**Comment by Yousei9** [comment]
Version: 1.10.13
Date: 2019-07-27
  Features:
    - Encoded position signal for carriage types https://forums.factorio.com/viewtopic.php?f=214&t=73122

**Comment by JonAdamsFromNC** [comment]
Of course, in a version a week old... Sorry for the waste, and thank you for all the effort put into your mods!
