### ISSUE TITLE
Integer overflow?

### ISSUE THREAD

**Issue by MatthewIsAwesome** [Yousei9/Logistic-Train-Network#196]
**Error message**  
![image](https://user-images.githubusercontent.com/30124354/66258344-15502880-e79c-11e9-915b-b6e13e7953f0.png)

**To Reproduce**  
(Not 100% Sure): Set stop timeout/delivery timeout to a very high number

**LTN version**  
1.11.1

**Log file**  
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/3693532/factorio-current.log)

**Comment by MatthewIsAwesome** [comment]
![image](https://user-images.githubusercontent.com/30124354/66258524-0d918380-e79e-11e9-937a-d69025a4752a.png)
May be related but also an issue

**Comment by Yousei9** [comment]
I was able to reproduce and fix a different error with insane settings of updating 100 stops each tick.
```
Error while running event LogisticTrainNetwork::on_nth_tick(1)
invalid key to 'next'
```



> 
> 
> ![image](https://user-images.githubusercontent.com/30124354/66258524-0d918380-e79e-11e9-937a-d69025a4752a.png)
> May be related but also an issue

That's just my lazy way to show that min and max length hasn't been set.

**Comment by zefir01** [comment]
Hi. In version 1.11.2 error:
```
  73.327 Error MainLoop.cpp:1195: Exception at tick 1927868: Мод LTN - Logistic Train Network вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event LogisticTrainNetwork::on_nth_tick(2)
Value outside of range in property tree at ROOT[2].ticks
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:558: in function 'ProcessRequest'
	__LogisticTrainNetwork__/script/dispatcher.lua:98: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20>
stack traceback:
	[C]: in function '__newindex'
	__LogisticTrainNetwork__/script/dispatcher.lua:558: in function 'ProcessRequest'
	__LogisticTrainNetwork__/script/dispatcher.lua:98: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20
```

occurs when specifying a negative amount of a resource at a request station and creating a delivery.

**Comment by Yousei9** [comment]
As stated before, I can't replicate this error on my side.
Please post saves reliably producing the error.

**Comment by zefir01** [comment]
[2.zip](https://github.com/Yousei9/Logistic-Train-Network/files/3787601/2.zip)
to reproduce, enable combinator.

**Comment by Yousei9** [comment]
I finally figured out the issue.

Stop using insane high values in Depot inactivity or Stop timeout.

**Comment by zefir01** [comment]
thanks. it works.
