### ISSUE TITLE
My trains are being stupid

### ISSUE THREAD

**Issue by Smario9000** [Yousei9/Logistic-Train-Network#198]
The issue I am having is that my trains are going to my Requesters instead of my providers

Here is how I have it set up
Type.          Name
provider     coal pick up 1   
Requester. Coal drop off 1
Requester. Cold drop off 2

This is how my trains set up task

Go to Coal drop off 1 deliver to coal drop off 2
Vice versa

But they never go to Coal pick up 1

The trains are connected together so it can route to all three points with no issue

**To Reproduce**  
I don't know how to reproduce  but my guess would be have one train stop with a provider and two requesters

**LTN version**  
1.11.6
Factorio ver. 0.17.78 (build 47844 win64 steam

I can send you my setup if you need my save file to help solve the issue

I'm not using that many mods

But thank you for taking the time out to read this and see if there was anything you can do to help with the issue 
thanks

**Comment by Yousei9** [comment]
Check your combinator settings, especially thresholds.

**Comment by Smario9000** [comment]
What do you mean I have a threshold set but their set low
And both of the requesters have negative I use than the provider has a positive number

**Comment by Yousei9** [comment]
Trains trying to pick up from requesters means LTN sees a positive number. See multiple older forum threads about this.

Trains not picking up from a provider either has it not provide more than provide threshold, or it is not valid with a depot, requester combination. See train length and Network ID on the forum.

**Comment by Smario9000** [comment]
What I don't understand is if it has a provider threshold it should be sent to a provider only same with a requester it should be set to only be able to request items

**Comment by Smario9000** [comment]
Thanks for the help

**Comment by Yousei9** [comment]
Stations can be provider and requester at the same time, even for the same item.
