### ISSUE TITLE
Lack of trains message tweaks

### ISSUE THREAD

**Issue by phreakscp** [Yousei9/Logistic-Train-Network#199]
This issue has two parts related to the lack of trains message:

1. Due to the amount of trains I have active, I set the message level in the mod settings to "Errors and Warnings" in order to see which parts of my factory need scaling.  However, this seems to disable the "[LTN] No train to transport items found in depots." message, which would mean i would need to build more trains.  I feel that this message should appear as an Error/Warning as it's an abnormal condition

2. The "lack of trains" message should also include the network ID(s), if possible

**Comment by Yousei9** [comment]
If I remember correctly "No train to transport items/fluids found in depots. Skipping item processing." messages used to be warning level.
Players running LTN with as few trains as possible then complained about the spam, so it was moved to notification.

The check behind these messages only looks at global variables counting total amount of itemstacks and fluid capacity of trains at depots. At this stage Network IDs are not available and would always be 0xFFFFFFFF (any) anyways.
