### ISSUE TITLE
Generic encoded positions are incorrect for bidirectional trains

### ISSUE THREAD

**Issue by robot256** [Yousei9/Logistic-Train-Network#200]
**Error message or bug description**  
Encoded position of generic locomotive and cargo wagon are based on the "front" of the train as assumed by the game engine, not the end of the train that entered the train stop.  This means that sometimes the two encoded positions do not match up.
![mismatched positions](https://user-images.githubusercontent.com/14794356/71642833-d0933b00-2c7f-11ea-90c5-e36e498e5c25.png)

**To Reproduce**  
Make an asymmetrical bidirectional train.  Have the train drive to the LTN stop with one end as the front, then the other.  The specific per-name encoded position signals will show the ordering reversed when you change the direction the train enters the station.  The generic per-type encoded position signals will show the ordering the same in both cases.

**LTN version**  
1.11.7

**Log file**  
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/4014182/factorio-current.log)

**Comment by Yousei9** [comment]
Thanks for noticing.
This copy paste error has been in there since I added position signals per carriage type.

**Comment by robot256** [comment]
Thanks! Happy New year!
