### ISSUE TITLE
constant desync

### ISSUE THREAD

**Issue by audenga** [Yousei9/Logistic-Train-Network#201]
everything worked fine until me and a couple of friends started using LTN requesters/providers and every couple of minutes we desync. to test this we picked up all the stations and were fine for about an hour until we placed them back down again and as soon as trains started to move around desync

here's the full desync report: https://www.dropbox.com/s/iq30gkvz2hlejrr/desync-report-2020-01-03_15-50-34.zip?dl=0

**Comment by Yousei9** [comment]
Sorry, desync reports are useless to modders.

Unless you can specify the exact steps to create a state that desyncs with only LTN and no other mods installed, there is no way I'll be able to find what's causing it.
