### ISSUE TITLE
game crashing issue.

### ISSUE THREAD

**Issue by Opiboble** [Yousei9/Logistic-Train-Network#202]
Issue started randomly, we are using the realistic electric train (https://mods.factorio.com/mod/Realistic_Electric_Trains) mod, and has been running with no issues for days. Suddenly it started crashing (link to image below). I updated LTN to 1.11.8 and still having the issue.
Just stand around and let the trains run and the game will eventually crash...

**Error message or bug description**  
If LTN caused an error message: https://cdn.discordapp.com/attachments/228338345443328001/662778825272197120/unknown.png

**To Reproduce**  
Steps to reproduce the bug - unknown, network has been running fine for days, crash started on 1.11.6 randomly, updated to 1.11.8 and still having issue. 

**LTN version**  
1.11.8

**Log file**  

[factorio-previous.log](https://github.com/Yousei9/Logistic-Train-Network/files/4021577/factorio-previous.log)

** Map File***
[pubmap.zip](https://github.com/Yousei9/Logistic-Train-Network/files/4021578/pubmap.zip)

**Comment by Yousei9** [comment]
That's a but with LTN Tracker.

**Comment by Opiboble** [comment]
Thank you!
