### ISSUE TITLE
Only highest stockpile is considered for delivery

### ISSUE THREAD

**Issue by Sil3ntStorm** [Yousei9/Logistic-Train-Network#203]
**No deliveries on multiple networks**  
If you have a resource available on multiple different networks, and a single requester on these networks, no deliveries take place if the network with the most stockpile of the resource is not capable of transporting said resource.

**To Reproduce**  
- Have a station on network 1 providing 200k water
- Have a station on network 2 providing 500k water
- Have a depot with a fluid train on network 1
- Have a depot on network 2 without a train (or a cargo train)
- Have a station requesting 100k water on network -1

**Actual**
Nothing happens, a warning is printed about there not being a train available on network 2.

**Expected**
Train from network 1 deliver `min(100k, trainCapacity)` water.

**LTN version**  
1.11.9

LTN currently takes the provider with the highest stockpile and then creates a delivery. If this fails it won't try any further. It should check whether the network that was chosen to fulfill the delivery has trains available for the delivery. If no train is available, try different networks capable of fulfilling the request, even if the stockpile of the resource is lower, but high enough to fulfill the request.

**Comment by Yousei9** [comment]
Working as intended. Depot, Provider and Requester have to be in the same network.
Making a connection from depot in network 1 and provider in network 2 would be an error.

**Comment by Sil3ntStorm** [comment]
Either you misunderstood the situation, or I misunderstood your reply.

In the example, each network has its own depot which is on that network and a provider capable of fulfilling the demand that exists in both (all in fact) networks. The only difference is that one network has a larger supply than the other.

The following would all be valid deliveries in above example:
- 100k Water from Station A (Network 1) to Station R (all networks) using Depot A (Network 1)
- 100k Water from Station B (Network 2) to Station R (all networks) using Depot B (Network 2)

However since B has more water stockpiled than A, LTN will attempt to deliver B -> R, and then fail because of no available train. It will not even consider running the alternative A -> R for which there is a compatible train sitting at the depot.

**Comment by Yousei9** [comment]
Now I understand what you expect.
I'm not going to rewrite of the entire core logic so LTN keeps trying different providers after failing to generate a delivery.
