### ISSUE TITLE
0.18.6 - Unknown key: entity-name.logistic-train-stop-lamp-control

### ISSUE THREAD

**Issue by HansTo** [Yousei9/Logistic-Train-Network#204]
factorio 0.18.6 with LogisticTrainNetwork_1.12.2

Noticed this small bug during scenario creation mode

![LTN_LampControl](https://user-images.githubusercontent.com/18010439/74581029-613b8700-4f5f-11ea-94be-43eeeea54f4e.png)

**Comment by Yousei9** [comment]
The editor always shows hidden items and entities.
Normal players are not supposed to see these so I'm not going to bother giving these an icon and name.

**Comment by HansTo** [comment]
ok - makes sense
