### ISSUE TITLE
Remove incompatible mod flag

### ISSUE THREAD

**Issue by elijahlorden** [Yousei9/Logistic-Train-Network#206]
Stop attempting to prevent players from using specific mods together for no real reason.  I noticed that the forked version of LTN tracker has been flagged as incompatible.  There is no reason to let a mod die if somebody is willing to take it over.
I'm aware that this tag has been removed in the recent update, but in case it is added again and for anyone who is interested:

Remove "!ptx0_LTN_Tracker" from line 10 in LTN's info.json file

"dependencies": ["base >= 0.18.0", "OpteraLib >= 0.2.0", "?cargo-ships >= 0.0.27", "!ptx0_LTN_Tracker"]

"dependencies": ["base >= 0.18.0", "OpteraLib >= 0.2.0", "?cargo-ships >= 0.0.27"]

This list is meant for actual dependency issues.  Let players choose what mods they wish to use.  If the 1.12.3 update breaks compatibility with the updated LTN tracker, just use 1.12.2.

**Comment by Yousei9** [comment]
Why are you complaining about a flag I just removed?
