### ISSUE TITLE
Output ordered items at requester train stop

### ISSUE THREAD

**Issue by Lerrrtaste** [Yousei9/Logistic-Train-Network#209]
## Example:
We want to have a bus supplied by multiple train stations, that would share a logic network for requests.
But as there is currently no way of knowing what/how many items have been dispatched already, we cant subtract that from the requesting signal.

This leads to duplicate orders, for example if there is a negative 8k coal signal: as soon as one train is on the way to fetch them, there is no way to prevent LTN from dispatching more trains until all train stations are in use.
## Suggestion:
Output already ordered items at the requester station's LTN ouput.
This way one could combine them with the requested amount and prevent unwanted deliveries.

## Screenshots
![image](https://user-images.githubusercontent.com/22920627/77362851-fcd7c880-6d51-11ea-93c5-27b4e619f0e0.png)
![image](https://user-images.githubusercontent.com/22920627/77363262-b8006180-6d52-11ea-943e-43e613800310.png)

**Comment by Yousei9** [comment]
Each station already has it's own buffer chest. Just work off the amount of items in those buffers on a station level.
