### ISSUE TITLE
Alert / incorrect pickup or incomplete delivery

### ISSUE THREAD

**Issue by dairen** [Yousei9/Logistic-Train-Network#211]
I try to use LTN Manager (Alpha) and i see many alerts
incorrect pickup and incomplete delivery

and it's true, many trains remains some multiples items in wagon
exemple: sometime, train return to depot with ore iron in wagon; if the next request is for ore copper, next time, i have train with multiple items in wagon

i don't know how to limit this
i try to maintain all requester to negative number and sometimes, i use in requester LTN, the provider set to 999M to remove the move between requester

**LTN version**  
1.13.0
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/4475167/factorio-current.log)

**Log file**  
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by Yousei9** [comment]
LTN Manager is a mod written and maintained by Raiguard.

**Comment by dairen** [comment]
the issue is not about the other mod but the fact that some wagon contains another item that this is selectionned

**Comment by Yousei9** [comment]
Its up to you players to build stations capable of loading correct cargo.
Check the design thread if you need help with station designs, Github is only for real bugs with LTN itself.
