### ISSUE TITLE
LTN crashes after 0.18.24 update

### ISSUE THREAD

**Issue by josephlee222** [Yousei9/Logistic-Train-Network#212]
**Make sure the bug is caused by LTN and not an interface recipient**  
Example of a bug in LTN Tracker:
```
The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID ???)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID ???)
```

**Error message or bug description**  
LTN crashes when a user logs in (After a short while).

**To Reproduce**  
1. Update to 0.18.24
2. Enter game
3. wait

**LTN version**  
1.13.1

**Log file**  
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/4621061/factorio-current.log)

**Comment by Yousei9** [comment]
Please read the stack trace. I didn't write an example in the bug report form for lulz.

**Comment by lottery248** [comment]
stack traceback:
	__LtnManager__/scripts/data-manager.lua:568: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	__LogisticTrainNetwork__/script/train-events.lua:157: in function 'TrainLeaves'
	__LogisticTrainNetwork__/script/train-events.lua:194: in function <__LogisticTrainNetwork__/script/train-events.lua:188>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/train-events.lua:157: in function 'TrainLeaves'
	__LogisticTrainNetwork__/script/train-events.lua:194: in function

**Comment by raiguard** [comment]
Yes, that is clearly pointing to LTN Manager being the issue, not LTN itself. Please come open an issue on the [LTN Manager repository](https://github.com/raiguard/Factorio-LtnManager) so I can fix it.
