### ISSUE TITLE
LTN Station Input light not working on ore

### ISSUE THREAD

**Issue by diamond-lizard** [Yousei9/Logistic-Train-Network#213]
**Error message or bug description**

When an LTN station is placed on ore, wire can not be attached to the LTN Station Input light and when hovering the mouse over the light, instead of the usual informational display reading "Logistical Train Stop Input" and showing a picture of the light, the informational display shows the name and picture of the ore it is on (for example, "Stone").

Please see the attached screenshots.  In the screenshots, the station on the left is on ordinary ground, while on the one on the right is on stone.

**To Reproduce**

1 - Place an LTN station on some ore.

2 - Try to attach a wire to the station input light, or just hover your mouse over it and look at the information display on the right.

**LTN version**

1.13.3

**Screenshots**

LTN station not on ore - normal behavior:

![ltn-input-not-on-ore](https://user-images.githubusercontent.com/31175456/82152958-327dc700-9854-11ea-9fcc-70706f605cc0.png)

LTN station on ore (on stone) - broken input light:

![ltn-input-on-ore](https://user-images.githubusercontent.com/31175456/82152970-40334c80-9854-11ea-922c-c491b42ba4b4.png)

**Comment by Yousei9** [comment]
Thanks for the report.
Seems like giving IO Entities no collision layer made the game shuffle them under ores somehow.
