### ISSUE TITLE
"Not enough trains in depot" should be a "warning"

### ISSUE THREAD

**Issue by RalfJung** [Yousei9/Logistic-Train-Network#217]
Fairly frequently when I wonder why there are not enough resources somewhere, it turns out the problem is that the depot had no free train. I noticed that when logging is set to "notifications", LTN actually prints a message in that case. However, to avoid getting a sound for every single delivery, I set logging to "warnings & errors". I feel like, if "no station providing X" is a warning, then "no free train in any depot" should be a warning, too.

So, could you make it such that "no free train available" is also sown when logging is set to "warnings & errors"?

**LTN version**  
1.13.9

**Comment by RalfJung** [comment]
(The "bug" label was auto-added. This is really a feature request, not a bug.)

**Comment by Yousei9** [comment]
The Bug label is added when starting a bug report instead of "Open a blank issue."

no train messages where warnings until I got nagged to change it to notification.

**Comment by RalfJung** [comment]
> no train messages where warnings until I got nagged to change it to notification.

I'm sorry I don't understand your comment here. Or did you mean "change it to warning"?

If "your network doesn't work because you don't have enough trains" is not a warning, then *what is*?

Clearly there is a distinction between "normal delivery happened, all is good" on one side, and "something went wrong: not enough resources/trains" on the other side. Can we agree that those two kinds of notifications are different in severity?

I think the mod would be improved greatly by providing a way to see the latter message and not see the former message. Whether you want to call it a "warning", or whether maybe normal delivery messages should be called "verbose", there should be a way to silence the latter without silencing anything exceptional.

**Comment by RalfJung** [comment]
> 2: Notifications (default) Print basic information like missing resources or generating deliveries.
> 3: Detailed Messages Print detailed information about finding providers and trains.

So maybe an alternative that you could live with is to move "generating deliveries" to (3)? Basically, what I think is not great here is that (2) mixes things that require immediate action (not enough resources! not enough trains!) with things that do not (normal deliveries).

**Comment by Yousei9** [comment]
I've started a poll https://forums.factorio.com/viewtopic.php?f=214&t=86051

**Comment by RalfJung** [comment]
Thanks. :)
