### ISSUE TITLE
Idea/Request: Timeout on loading, but not unloading.

### ISSUE THREAD

**Issue by perkinslr** [Yousei9/Logistic-Train-Network#219]
LTN has a global option for adding an "or X seconds passed" condition to all stops.  It would be nice if there were an option to add that condition on the pickup stations, but *not* on the dropoff stations.  

Once in a while, especially when first deploying a rail system, poorly balanced loaders, power brownouts, or other factors will cause a train to fail to load or unload in a predictable length of time.  Rather than having to manually order the train to the next stop (especially in the case of brownouts, with coal trains), it would be nice if there were a way to have the train move on automatically after a delay.  However, the same brownout condition on the dropoff side (or trying to always keep a train dropping things off to help with latency) means you end up with a train returning to the depot with cargo (and then going elsewhere and mucking up your supply lines).  Being able to selectively add a "time passed" condition would solve this issue.  

You *can* use the "wait for green signal" condition to similar effect, but with more combinators, which is not particularly U/S friendly.

**Comment by Yousei9** [comment]
Controlling trains with combinators is as customizable and granular as possible. I see no reason to add a layer somewhere between all stations and that.
