### ISSUE TITLE
Requester Priority

### ISSUE THREAD

**Issue by Opiboble** [Yousei9/Logistic-Train-Network#22]
Again, thanks for the awesome mod! Now on to my idea/request:

Set priority of request stations - Higher priority gets delivers first. Why? Because I am tired of plastic going to the circuit factory before batteries, lol. I think it would give us a little more control in where we want materials first. : )

**Comment by Yousei9** [comment]
Sounds to me like either your circuits are over-producing or your plastic is under-producing,
Prioritizing would only change shift your bottleneck from batteries to circuits.

**Comment by Opiboble** [comment]
Ultimately it is an oil problem with my map, have gone many kilometers in all directions, and still no oil to be found :/ Thought I would throw out a request for enhancement as I struggle to find oil :D

**Comment by Pasukaru** [comment]
You could just use the circuit network for that.
Set the battery station to request plastic, but only if the circuit station has X or more plastic buffered.

**Comment by Yousei9** [comment]
I've set production limits to each module.
e.g. if batteries < 500 produce until > 1000
It lets me find bottlenecks while keeping modules from overproducing in case i overbuild them.

**Comment by Opiboble** [comment]
@Pasukaru - so basically have a circuit wire run between them and set logic to for that? .... I might, but boy is that going to be a long wire, lol.

**Comment by Yousei9** [comment]
Implemented in 1.5.0
