### ISSUE TITLE
Idea/Request: Set target fill percent for cargo wagons

### ISSUE THREAD

**Issue by perkinslr** [Yousei9/Logistic-Train-Network#220]
Most of the issues with LTN crop up when asking for full wagons of goods (especially mixed type goods).  You end up with inserters holding the *wrong* item type for the next train, one wagon filling up and being unable to hold the last item it needs, and so on.  

A simple solution is to add a global setting to pick how full to fill wagons.  For example, setting it to 97.5% will leave one empty stack per (standard) cargo wagon.

**Comment by Yousei9** [comment]
See https://forums.factorio.com/viewtopic.php?f=214&t=61852

**Comment by perkinslr** [comment]
That is not actually a duplicate.  The linked forum post wanted a way to say "send all the requested X when Y percent of them are missing from a requesting station".  This is "pretend the cargo wagons are only Z percent of their real size, so any overflow has a slot available".  

The former can be easily solved (per station) with a combinator.  The latter cannot be (in the general case).  I suppose you could restrict a station to only trains of a fixed length (instead of all trains up to a max size), and then use... 2? combinators to only request a maximum of some percent of the train wagon size at a time.  The number of combinators increases geometrically (7 needed to handle 2 types) if you have multiple item types requested, and can only approximately be solved *at all*.  It also, as implied above, fails if you have different sized trains which might want to pick up from a station, as you'd have to scale the numbers requested by the size of train en route.

**Comment by Yousei9** [comment]
My bad, the later seemed too weird for a request with Locked Slots already doing exactly that for ages.

**Comment by perkinslr** [comment]
Oh! Not sure how I missed that.  I *think* I assumed from the name that it would lock the slots like the red X does, which wouldn't really help.  Anyway, nevermind I guess, you already thought of it.
