### ISSUE TITLE
Request: Allow independent Fluid/Item Request Thresholds

### ISSUE THREAD

**Issue by PiggyWhiskey** [Yousei9/Logistic-Train-Network#221]
I use LTN Providers with a single items, and LTN Requesters with many, with isolated production of every item.
I run into issues when a Requester needs Fluid and Items (Bob's Steel recipe needs Oxygen and Iron Plate)  (Running 1-2-0 Loco's)

So I request 75k Oxygen to 75% fill 4 tanks, and 8k Iron, but have the request threshold at 4k.
This results in fluids coming in dribs and drabs. If I accommodate the fluid(50k request), the Iron never get's requested.

AFAIK there isn't a way to have different Request Thresholds unless I do duplicate stops.

I've attempted to use red for items, and green for fluid, each with their own constant combinator, but the LTN stop doesn't differentiate between them.

Is there any suggestions how to manage this?

**Comment by Yousei9** [comment]
From the [manual](https://forums.factorio.com/viewtopic.php?f=214&t=51072):
>  Request Stack Threshold (optional) - Missing amount of item stacks triggering a delivery. Takes priority over Request Threshold.
Provide Stack Threshold (optional) - Amount of item stacks required to act as provider. Takes priority over Provide Threshold.
