### ISSUE TITLE
Feature: Add LuaTrain to remote calls

### ISSUE THREAD

**Issue by StephanSteinert** [Yousei9/Logistic-Train-Network#222]
Hej,

would it be feasible to add the reference to the whole LuaTrain to the event data of the remote calls on_delivery_completed and on_delivery_failed?

Cu, steinio.

**Comment by Yousei9** [comment]
Firstly, that's a request, not a bug.

It's possible to add LuaTrain to on_dispatcher_updated, on_delivery_pickup_complete, on_delivery_completed
Error events like on_delivery_failed can't contain a valid LuaTrain as that's one of the error sources.

I choose against passing LuaTrain in only some events. Having a local train table is faster than passing train objects around in events.

**Comment by StephanSteinert** [comment]
Hej, yeah i saw to late, that on_dispatcher_updated transmits all LTN trains and i can work with that.

The bug flair was added by Github and i didn't found an option to remove it.

See ya.
