### ISSUE TITLE
Extension for Signalized Couplers

### ISSUE THREAD

**Issue by Technickfreak** [Yousei9/Logistic-Train-Network#223]
I think it would be cool if the mods "LTN - Logistic Train Network" and "Signalized Couplers" can work together.

so that stations can order 3 empty wagons
and when these are loaded
enable a locomotive to pick up the wagons.

At first glance, these are only tasks for the LTN programmers, but I easily overlook something.

Link to the other mod:
https://mods.factorio.com/mod/Signalized_Couplers

Link to the other issue:
https://github.com/digital-pet/signalized-couplers/issues/4#issue-679577851

**Comment by Yousei9** [comment]
I don't think that's feasible.

1. Tracking carriages in addition to items and fluids will be a pain.
It'd had to be done through new virtual signals, then type virtual would have to be treated like item and fluid....

2. de-coupling requires more than 1 stop.
Possible with but it'd require one specific layout of stops and dual headed locomotives.

**Comment by Technickfreak** [comment]
with a little bit of drizzling, this is already possible
but only if one of the locomotives remains open.

I also have an MP4 file that shows how the train goes.
but the file is unfortunately too large to add to it. (277MB)
![Factorio Screenshot 2020 08 15 - 18 33 08 41](https://user-images.githubusercontent.com/65553685/90316901-cfb8cc00-df25-11ea-8adf-0fca8c6e1018.png)

**Comment by mrvn** [comment]
See https://github.com/Yousei9/Logistic-Train-Network/pull/273 for a way to order empty trains. Sounds like that is exactly what you need.
