### ISSUE TITLE
Strange barrels added to the game

### ISSUE THREAD

**Issue by Dominiquini** [Yousei9/Logistic-Train-Network#228]
**Make sure the bug is caused by LTN and not an interface recipient**  
The latest version of LTN (1.14.1) added some strange elements to the game. Some barrels (full and empty) of unknown types.
I tested an older version (1.13.10) and these items no longer appeared!

**Error message or bug description**  
![factorio_KDcVNc4pvE](https://user-images.githubusercontent.com/1180808/91616275-bff4ab00-e95b-11ea-88b4-30257a1f4b9f.jpg)

**To Reproduce**  
- Open a new game with the last version of LTN
- Enable cheat mode ("\cheat all")
- Open player crafting GUI on Intermediates Products tab
- See 8 invalid barrels

**LTN version**  
1.14.1

**Log file**  
---

**Comment by Yousei9** [comment]
Those fluids are required to have alert icons without showing up in signal list.
By enabling cheat mode you see hidden items.

**Comment by raiguard** [comment]
Couldn't you create items that have no category as well? Then they would only show up in the queation mark category when in the map editor.

**Comment by Yousei9** [comment]
I used fluids so they wouldn't show up in that tab, but forgot about auto barreling.

**Comment by raiguard** [comment]
Ah, I guess not showing up whatsoever is preferable to showing up at all, even if it's hidden away in a small corner.

**Comment by RalfJung** [comment]
> By enabling cheat mode you see hidden items.

FWIW, they were visible even without cheat mode. I see strange barrel recipes in my assembly machine 3.

Space exploration has notifications for meteor strikes with a custom icon, and they don't show up anywhere as far as I can tell -- maybe there's a way to replicate that here.
