### ISSUE TITLE
Incorrect (?) "incomplete pickup" messages

### ISSUE THREAD

**Issue by RalfJung** [Yousei9/Logistic-Train-Network#230]
**Error message or bug description**  

In our multiplayer game, since the recent update, we fairly regularly see a message saying that a train didn't pick up enough cargo. These messages are always about the same provider station. However, as far as I can see, all trains leaving there *do* get enough cargo. Certainly, none of them runs into the 180s timeout; they all leave the station because the "cargo >= requested" condition in the train schedule is satisfied. I think this means they definitely got enough cargo.

Also, if they truly did not pick up enough cargo, then LTN manager (which we also have installed) would complain as well.

So I think the message is just wrong. Unfortunately, I have no idea how to debug this.

**To Reproduce**  
In case it helps, here's a blueprint string of our station:
```
0eNrtW9tuqzgU/RceR3AE+AbVaL5i3kZHEUmcxCoBZEyn1VH+fQwkISXeAeMqo2qmD61IYHl7X9a+4P7y1nnDKykK5b388sSmLGrv5a9fXi32RZa3n6mPinsvnlD86PlekR3bq78zyQ9lU/NgndVi4518TxRb/u69RCd/8mmZifzmkfj00/d4oYQSvF+9u/hYFc1xzaXGvD5ZK/3s/qCCDsL3qrLWT5VFu5RGwjj1vQ/9QIxOrRwjnPiKw98ryes60HBFXZVSBWueKwMgIT/IGTL+QbTMWyH5pr+DGpZAC5bA8BLY97RJlCzz1ZofsjdRyvaxjZCbRqiV/m57xdoJWavVhOrXmVJcfrTab22tstbwcah/2g+OVSYz1a7h/d7dcl6HF9k656utqNu/3ouSDR++lTzbrg5ZsW3lUVoh2oi7LK9vbrl80d97LLcaJOxlKPq91q3IUftL8u2tEwh9FaHTz5PJovhO3XmZbfU3D9WM75R80VVRNcozrEMWmJXZeQ5dsAS1W4I57QLpJQygyU1wljLb80A71WtsCs7BAqQT12T9veS8uLM/A+yfXhc/8q1ojgHPNaAUm6AqtaMaZBhUhs37icJPPBWcA8oAxSahFhCXGSi+Aco2r8FO5DqMA1HUXCqzu4cjZd/4RvyYVdrwXJW7VVlxzQbdE9H8WI1jwFYRAtOHKVrPwifzV0Y3i3aSJG1iMToUJpCQ2NajSDTpBm7sAaHeE0aj86ncy1L/nYHbu8WZ+cpGAdQXsSUBntgFeDIyHY4g+wx0UzXHyhiWZxGopdvPSaa7vNHiDQpp8l3T+ka20R9/yqnjfPqHd7LIdym0/XT29tk33v6dO0D8H4f2DMuMQJELw7JnM+yI6CikHqe8QZ+7q2i0qwhKJPGQSCpRaToqg570TFaPr9tJ74prEza2d6jUKCRxUX36XNXTkeoR6FDUZVfJc3dFxmECJZWYWbQRCWQiOt1GxMmCSiCFvYJ+dXvYM/pnKo++bXcYp/bqpg+C0Njwh5MZ+UpBKPry7n5+Ro6ALt+mTCNQXYKiT5Rs0gIatGAuaFFsgRECGMi6IcSTcuHlTSaISazTjHYeE5ALIXda/BcJGUOBi9jyLgxUeeLWL3W40xSP0kkvHvggNouKQ4tIgDCiBW0bwtZzmc8WJRga1MX2Dm+c4WLk4vDxUx0ejesqDKoHu+wKPXVXeDxnwVBWwGTBxAeR+aKQcSdE4ZFPNBabQuUgdpysnL1scrKC2dxmHpFvPcsYcQQ0e8OJPUeYuS91iSb83GjCY/WEgHpI6LKr5w6B8Z3RoQkOiex7r3sTzei9SOzSexmX/L/3ggfpBLn0XgZ1m9bAS2ocZlfj4PFcCmyCCJnN5994No3ZbH1Qez43DmcJc2G+544xNX2P1JNA6klcdvXckTNhc4sn4vBKFsFvjUwykXuZRh/Qgee6BhQsDsk4C6NwCpxBdqX27ySQcYRMI4cu2E6VqcFpfXAG5M9LATRecjpD62I6mdMhu6zFflov9KGescv7WZSaG3BKHLuIZNa8gQ4km0mhDkeutB40va9F0dH7o4DD8cnMGgPUkHrqB7nnTUjVdKckLp7f3RHwbHNoc0/NW5jVkIIC7ds3VOT9ph/tOyVbcIvUxdpM5Xvx3ChgUNFKmXWIY+P4jiYu58VweAny//wJMZiEUicNA8NEFrpQBogaOaECM3FmP3rDxtEbczrciIFBJcNOqMCpNOZ05gZEpU6okAYGNsnLvahbAm8NVQS6q6mC8wDp0QE0TMwHR+dEjqFIMgYSSx5K2Seoh8mGfAlbQdkgKz7UQRT7yVbH95qa66XyUtY9UVm+AvucJBLoJQZLHynsQXeI5x0C7ohyJ8vjqkO9cG53sWqXqPh2vvr+tOkBxz7TNQN+28ac07mpUkns62JsPnEaOTEGcJ4uiZ1iG0IdOPPilLOLMzrzNHjfNwLn9u/snasiqGT5JnQtGqiD3uihzM8DguaS6yeO8xtB83LzyrdBnZc6vd/A3Zzzn4111FHSx0rOi7063OChKx6ywMvep/HwArzbnZIrEunqzNmcAraSCbY+i9x5jQnK/o0zNg5jEvupDtZtl24nuzrz5eY/TnzvTfttP71I9HI4ZZRFISX0dPoHDM8AvA==
```

From my observations, this only affects the fluid requests satisfied at this fluid-solid combined station. These fluid requests are typically not for full trains, they are from various uranium mines requesting 10k sulfiric acid.

Strangely, when I load the same map in single-player mode, so far I was not able to see these messages.

**LTN version**  
1.14.2

**Log file**  

Log from a multiplayer session where the problem definitely occurred:
[factorio-previous.log](https://github.com/Yousei9/Logistic-Train-Network/files/5149313/factorio-previous.log)

**Comment by Yousei9** [comment]
That logfile didn't have LTNs debug logging enabled.

**Comment by RalfJung** [comment]
I guess? I didn't know such an option even existed or that I was supposed to enable it.^^ How would I do that?

**Comment by Yousei9** [comment]
https://forums.factorio.com/viewtopic.php?f=214&t=60889
> turn on logging in options - mod settings - map - enable debug log

**Comment by RalfJung** [comment]
I can ask the host of our multiplayer game to enable that... I hope it won't be too heavy performance-wise or so? The map that we play on is rather big...

**Comment by Yousei9** [comment]
It's very performance heavy, that's why its an option you have to toggle on.
But Factorio mp games can be saved and loaded in single player.

**Comment by RalfJung** [comment]
> But Factorio mp games can be saved and loaded in single player.

I know. And as I said above, in single-player so far I was unable to observe this problem.

**Comment by RalfJung** [comment]
I managed to catch a logfile while playing multiplayer and the issue happening. I immediately ended loging after the issue came up, so the problem should be somewhere at the end. The train stop from which the supposedly not loaded train left is called "Sulfur 01 Out". I think the bad train was "ReahtLegionnaire" but I am not sure.

[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/5175504/factorio-current.log)

**Comment by RalfJung** [comment]
The only odd thing that I noticed so far is this:
```
2847.487 Script @__LogisticTrainNetwork__/script/stop-update.lua:290: (UpdateStop) Sulfur 01 Out {0xffffffff} updating delivery count with overloaded train 439 inventory: fluid,sulfuric-acid 10133.333333333
```
Probably the train got more sulfiric acid than expected. But that is not avoidable; we shut down the pumps once the requested amount is in but with the speed liquid are being loaded, it ends up pushing a few hundred more in anyway. The error says that not enough cargo was put in; does that error also occur when a bit too much is put in? Then probably this needs some more slack for liquids.

**Comment by Yousei9** [comment]
I found a rare occasion where for some reason the lsb differed on seemingly identical floats.

**Comment by RalfJung** [comment]
Thanks a lot. :)
