### ISSUE TITLE
After updating LTN, temporary stops were not generated properly

### ISSUE THREAD

**Issue by codemage** [Yousei9/Logistic-Train-Network#231]
EDIT: Sorry, mis-timed enter keypress submitted this too early.

Anyway, after a recent update to LTN 1.14.2, some trains seemed to get routes without the temporary stops necessary to disambiguate same-named stations. Since this didn't cause issues until trains timed out when attempting to unload at the wrong station and returned to the depot full of stuff, I wasn't able to pin down exactly when the issue started or get a log file. Renaming the affected stops seemed to fix things, and temporary stops were still being created on at least some routes, so I also don't have a good way to reproduce this issue. Still, I figured I might at least try to report it in case other people come along who can provide better details.

**Comment by Yousei9** [comment]
That's correct, existing train schedules are not migrated when updating to 1.14.
LTN had to work with unique stop names until that point. Usually deliveries complete before players start renaming all stops.
