### ISSUE TITLE
Error when cutting entities in Editor mode

### ISSUE THREAD

**Issue by sparr** [Yousei9/Logistic-Train-Network#232]
**Error message or bug description**  
```
Script @__LogisticTrainNetwork__/script/dispatcher.lua:30:
(OnTick) Invalid global.tick_stop_index 52266 in global.LogisticTrainStops. Removing stop and starting over.
```

**To Reproduce**  
Open /editor and ctrl+x a LTN stop with the "instant" construct and deconstruct options enabled in the editor settings.
Does not happen every time, but often enough to be usefully reproducible.

**LTN version**  
1.14.3

**Log file**  
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by Yousei9** [comment]
Cant reproduce in current builds without additional mods messing with composite entity building.
