### ISSUE TITLE
Request, please make time of condition_finish_loading into a mod setting.

### ISSUE THREAD

**Issue by staviq** [Yousei9/Logistic-Train-Network#233]
Hi, could you please turn this hardcoded value ("ticks") into a mod setting ?

local condition_finish_loading = {type = "inactivity", compare_type = "and", ticks = 120 }

I changed it to 1s (60) for myself and everything seems way more fluent now and i like it very much that way.

I do not want to ask you to change your values, and do not want to edit the mod manually every update either, so i think a reasonable solution would be to make it into a user changeable mod setting.

If it's possible, i'd really appreciate that, thanks.

**Comment by Yousei9** [comment]
Either slow early inserters or stack inserters from sparse belts can easily take more than 1s to trigger inactivity.
Allowing players to break a working part of LTN for a pathetic 1s gain doesn't sound very appealing to me.

**Comment by Aberro** [comment]
I guess that's the reason why sometimes my trains ends up with few items of unintended cargo? I've noticed that train leaves before filtered inserters are able to insert their items, so with mixed cargo stations next train get whatever that inserter is holding.

**Comment by Yousei9** [comment]
Enable circuit conditions to lock trains in with a red signal.
