### ISSUE TITLE
Output items in the requester stations

### ISSUE THREAD

**Issue by Dominiquini** [Yousei9/Logistic-Train-Network#235]
It is possible to output the current requested items in the "Logistic Train Stop Output" at the requester stations?
You already output this in the provider stations!

Thanks

**Comment by Yousei9** [comment]
That was how very early LTN did it.
For combinator setups the current way of outputting desired inventories is more convenient.

**Comment by Dominiquini** [comment]
I was thinking it could be useful on stations that request multiple items, since stack filter inserters have only one filter slot!
But I think I don't even need to use filter inserters to unload trains!

Thanks.

**Comment by Yousei9** [comment]
controlling stack filter inserters was exactly the reason for having desired output.
With desired inventory output loading and unloading requires only 1 combinator to cycle infinite number of items.
With items to unload it takes 2-3.

**Comment by Dominiquini** [comment]
I'm quite new to the game and I didn't understand what you said. But as far as I can tell, the station does not return anything, neither the desired inventory nor the items requested. Just the configuration of the train parked at the station!
I'll look on YouTube for more tips on how to use this mod.

Thanks for the answer!
