### ISSUE TITLE
Depot duplicate will cause traffic jam

### ISSUE THREAD

**Issue by caoliang313** [Yousei9/Logistic-Train-Network#236]
**Make sure the bug is caused by LTN and not an interface recipient**  
Example of a bug in LTN Tracker:
```
The mod LTN - Logistic Train Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_tick (ID ???)
The mod LTN Tracker caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID ???)
```

**Error message or bug description**  
If LTN caused an error message: screenshot or text of that message.
If something did not work as expected: Description of the behavior and what you expected instead.

**To Reproduce**  
When my trains work is finished,they want to go to the same Stop......
DepotNetwork ID is "-1"
**LTN version**  
1.14.5

**Log file**  
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by Yousei9** [comment]
Not a bug.
Make depots big enough.
