### ISSUE TITLE
Error/crash when using hotkey for disabling/enabling Dispatcher (ctrl-shift-D)

### ISSUE THREAD

**Issue by MoneyAllDay** [Yousei9/Logistic-Train-Network#237]
**Error:**
```
The mod LTN - Logistic Train Network (1.14.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::ltn-toggle-dispatcher (ID 206)
The mod Todo List (18.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Todo-List::on_runtime_mod_setting_changed (ID 59)
__Todo-List__/control.lua:33: bad argument #3 of 3 to '__index' (string expected, got nil)
stack traceback:
	[C]: in function '__index'
	__Todo-List__/control.lua:33: in function <__Todo-List__/control.lua:32>
stack traceback:
	__LogisticTrainNetwork__/script/hotkey-events.lua:13: in function <__LogisticTrainNetwork__/script/hotkey-events.lua:8>
stack traceback:
	[C]: in function '__newindex'
	__LogisticTrainNetwork__/script/hotkey-events.lua:13: in function <__LogisticTrainNetwork__/script/hotkey-events.lua:8>
```

**To Reproduce**  
I pressed ctrl-shift-D once and the game just crashed, after testing it again the game crashes every time i use the hotkey.

Since i'm rebuilding the rail network i kept disabling/enabling the dispatcher via the options, i thought maybe there was a shortcut so after looking for it and using it the game just crashed like i said above.

**LTN version**  
1.14.6

**Log file**  
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/5388852/factorio-current.log)

**Comment by Yousei9** [comment]
```
Error while running event Todo-List::on_runtime_mod_setting_changed (ID 59)
__Todo-List__/control.lua:33: bad argument #3 of 3 to '__index' (string expected, got nil)
stack traceback:
	[C]: in function '__index'
	__Todo-List__/control.lua:33: in function <__Todo-List__/control.lua:32>
```
That's an error in Todo-List.

**Comment by StephanSteinert** [comment]
Additional info: the mod creator has to check for player_index as scripts can raise this event without it - see https://lua-api.factorio.com/latest/events.html#on_runtime_mod_setting_changed

This will not be the last report of this kind I bet, sadly. Mods I use which had this issue got fixed really fast.

**Comment by JonasJurczok** [comment]
Hey,
sorry for reacting so late.
I'll fix it asap.

**Comment by JonasJurczok** [comment]
It should be fixed now.
@MoneyAllDay if the problem comes up again please open an issue at https://github.com/JonasJurczok/factorio-todo-list/issues
