### ISSUE TITLE
Item symbols in notifications

### ISSUE THREAD

**Issue by tmechen** [Yousei9/Logistic-Train-Network#238]
currently factory item symbols are shown double: both the symbol and the name (see image)
![grafik](https://user-images.githubusercontent.com/9123876/98470223-928e6e00-21e4-11eb-8610-27f39106ed3b.png)

is this intended behavior (im pretty sure i have seen videos where only the icons are shown) and if not, is this a problem with the mod or with factorio itself?

**Comment by tmechen** [comment]
nvm. not a bug, not a problem. i just used the [item=iron-plate] richtext, instead of the images [img=item/iron-plate]

**Comment by asdkant** [comment]
@tmechen can you detail how you solved this? I have a station named `[item=logistic-train-stop][item=iron-plate][item=logistic-chest-requester] ([item=electronic-circuit])` and it renders like this:

![image](https://user-images.githubusercontent.com/3915542/103311030-046e8100-49f8-11eb-8e90-f449072db1d4.png)

**Comment by raiguard** [comment]
@asdkant Instead of doing `[item=iron-plate]`, do `[img=item/iron-plate]`. That will only render the icon instead of the interactive rich text.

**Comment by asdkant** [comment]
@raiguard that's more of a workaround than a fix, since the item palette ingame uses the `[item=iron-plate]` style.

the rendering for this is an issue with LTN, or with the base game? (so I know if I have to raise the issue with the base game devs)

**Comment by raiguard** [comment]
It's the base game. There are places where the base game will expand rich text like that, and other places where it won't. The chat is one of those places.

**Comment by nil** [comment]
Yes, but couldn't LTN stations be automatically renamed?
