### ISSUE TITLE
LTN output lights have collided where they would not have collided before

### ISSUE THREAD

**Issue by pigheadx** [Yousei9/Logistic-Train-Network#243]
The collision box of LTN output lights is different from before, or the curved rail, or the change of collision mash?

![Factorio1 1 6_LTN1 15 0_flib0 6 0](https://user-images.githubusercontent.com/23497311/102724431-71c04900-434a-11eb-83f7-a7a9b4429294.png)
Factorio1.1.6, LTN1.15.0, flib0.6.0

![Factorio1 0 0_LTN1 14 6_flib0 5 0](https://user-images.githubusercontent.com/23497311/102724435-74bb3980-434a-11eb-8101-65d988282597.png)
Factorio1.0.0, LTN1.14.6, flib0.5.0

**To Reproduce**  
Build a station as shown above

**LTN version**  
1.15.0

**Log file**  
Not a crash.

**Comment by Yousei9** [comment]
Rails not colliding with stops in this configuration was a bug that has been fixed with 1.0.
Now rails and all LTN stop entities share collision layers.
