### ISSUE TITLE
Request: Use gps rich-text to log to & from station positions 

### ISSUE THREAD

**Issue by aSemy** [Yousei9/Logistic-Train-Network#246]
When there are a large number of stations and one is misconfigured, it can be very difficult to figure out where the problem is. Recently I've had a problem where I'll get a train full of Copper Plates wandering around, with no apparant cause. 

I'd love to be able to click on a log message to go directly to a station, so that I can check it very quickly, even if I have many stations with the same name.

I edited the code and created an example: ![image](https://user-images.githubusercontent.com/897017/103219747-dec17900-491e-11eb-8c86-875d915e4c0a.png)

Setting message-level to 2 can help, but personally I've got a large number of stations (which, even if they weren't identically named, would still be hard to find), so when I see a delivery has been created "from Provide: Copper Plates to Req: Copper Ore" obviously something is wrong, but it's really difficult to know why a train would want to go on that route! You don't get Copper Ore from Copper Plate providers.... And also I can't tell *which* stations the delivery is going to or from. There are tens of each!

---

In `dispatcher.lua` I edited 3 lines.

Under line 436, I added a `toGps` String variable 

```lua
  local to = requestStation.entity.backer_name
  local toGps = format("[gps=%s,%s]", requestStation.entity.position["x"], requestStation.entity.position["y"])
```

Under line 504 I added a `fromGps` variable

```lua
  local from = providerData.entity.backer_name
  local fromGps = format("[gps=%s,%s]", providerData.entity.position["x"], providerData.entity.position["y"])
```

And then I used these two variables in the `printmsg(...)` call on lines 609 and 601

```lua
  -- create delivery
  if message_level >= 2 then
    if #loadingList == 1 then
      printmsg({"ltn-message.creating-delivery", from.." "..fromGps, to.." "..toGps, loadingList[1].count, loadingList[1].localname}, requestForce)
    else
      printmsg({"ltn-message.creating-delivery-merged", from.." "..fromGps, to.." "..toGps, totalStacks}, requestForce)
    end
  end

```

---

I'm very happy with the outcome, it helped me figure out that I had a station that was misnamed (it was providing Copper Ore correctly, but was called 'Provide: Copper Plates' instead of 'Provide: Copper Ore', and the train couldn't handle that so it went to another station instead.)

However the log messages now become really, really verbose. Perhaps it could be a checkbox in the mod settings, "Enable station location in log"?

**Comment by Yousei9** [comment]
Makes sense.
I'll add it to the other good suggestions for improving messages.

Generally this is something that will always be easier to figure out using [LTNM](https://mods.factorio.com/mod/LtnManager).
