### ISSUE TITLE
Crash on Ctrl-Shift-D (disable dispatcher) and mod Auto Trash is installed.

### ISSUE THREAD

**Issue by kryojenik** [Yousei9/Logistic-Train-Network#249]
```
The mod LTN - Logistic Train Network (1.15.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::ltn-toggle-dispatcher (ID 174)
The mod Auto Trash (5.3.12) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event AutoTrash::on_runtime_mod_setting_changed (ID 59)
__AutoTrash__/control.lua:465: bad argument #2 of 2 to 'get_player' (string expected, got nil)
stack traceback:
	[C]: in function 'get_player'
	__AutoTrash__/control.lua:465: in function <__AutoTrash__/control.lua:459>
stack traceback:
	[C]: in function '__newindex'
	__LogisticTrainNetwork__/script/hotkey-events.lua:13: in function <__LogisticTrainNetwork__/script/hotkey-events.lua:8>
```

**Error message or bug description**  
This issue only occurs if the mod Auto-Trash is enabled as well.  I will be reporting to that mod also.
https://github.com/Choumiko/AutoTrash
https://mods.factorio.com/mod/AutoTrash

**To Reproduce**  
[AutoTrash-LTN-Crash.zip](https://github.com/Yousei9/Logistic-Train-Network/files/5904934/AutoTrash-LTN-Crash.zip)

This is a brand new start of a game with only LTN and Auto Trash mods.   Simply hitting Ctrl-Shift-D to disable the dispatcher will trigger the crash.

This initially occurred in a late-mid game with several mods and all the relevant techs researched.   Distilled it down and tested with Auto Trash and LTN individually.   Neither crash.   Crash only occurs when both mods are enabled.

**LTN version**  
1.15.0

**Log file**  
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/5904932/factorio-current.log)

**Comment by Yousei9** [comment]
Bug in AutoTrash and not LTN.
