### ISSUE TITLE
Possible bug in dispatcher: subtracting delivery from providers twice

### ISSUE THREAD

**Issue by iTob191** [Yousei9/Logistic-Train-Network#250]
While reading the dispatcher code, I found the following code segment:
https://github.com/Yousei9/Logistic-Train-Network/blob/6e75c16787cecfdd6b188d72a2bddadf80733352/script/dispatcher.lua#L644-L646
Unless I'm missing something, the delivery is subtracted twice from the providing station.
That segment was introduced in 0af115f0251c82c47f1eb6e7c1044f6aff1fa47d as part of the stack threshold implementation and I can't find any explanation except that this is a bug.

**Comment by Yousei9** [comment]
Seems like a very sneaky copy paste error that went undetected for 2 years.
I hope fixing it doesn't break any spacebar heaters.
