### ISSUE TITLE
Remove collision mask from "logistic-train-stop-controller"

### ISSUE THREAD

**Issue by jackhugh** [Yousei9/Logistic-Train-Network#253]
If an entity eg. rail overlaps the `logistic-train-stop-controller` after it has been built it will show collision error, however if the entity is placed first and then the ltn stop is placed it will allow it. This causes issues with bots building blueprints where this overlap happens, depending on if the bots decide to build the stop or the overlapping entity first.

**To Reproduce**  

LTN Stop placed first

![Screenshot (2)](https://user-images.githubusercontent.com/24830612/108067399-a0ac2000-7058-11eb-9c5b-17e1320e7951.png)

Overlapping entity placed first

![Screenshot (3)](https://user-images.githubusercontent.com/24830612/108067402-a1dd4d00-7058-11eb-8011-c5d80f9eaa55.png)

With `data.raw["constant-combinator"]["logistic-train-stop-lamp-control"].collision_mask = {}`

![Screenshot (5)](https://user-images.githubusercontent.com/24830612/108067403-a30e7a00-7058-11eb-8965-4ec9e6584330.png)

This is how I fixed the issue but there may be a better way.

**LTN version**  
1.15.2

**Comment by Yousei9** [comment]
I moved the controller slightly under the lamp, preventing adjacent lamps from automatically connecting.
![2021-02-16 173721](https://user-images.githubusercontent.com/8436934/108097313-43c55f80-7082-11eb-94aa-0297e4d94aca.png)

That would probably be enough, but I see no reason to keep collisions on the controller.

**Comment by jackhugh** [comment]
Thanks! It looks like the mask was only set to the rail layer before, so was probably only an issue with curved rail collision boxes.
