### ISSUE TITLE
Enhancement: New event on_depot_unexpected_cargo

### ISSUE THREAD

**Issue by keombre** [Yousei9/Logistic-Train-Network#255]
Hi, I'd like to suggest a new event (and maybe a new alert) for when a train arrives and/or leaves a depot with any cargo.

I'm making LTN cleanup and this feature would save me sooo much time :D

Example of the event prototype:
```
{
  train,
  station,
  cargo = { [item], count } }
}
```

**Comment by keombre** [comment]
Yup, that's what I'm doing, but I'd like to solve a situation when a train gets new cargo between the requester and depot.
I know it's a crazy edge case :D

To clean the depots I'm checking for diff in on_dispatcher_updated and cleaning any new deliveries. But it's ugly since I "steal" LTNs train before the delivery even starts.

**Comment by Yousei9** [comment]
Players would have to deliberately put loading systems in the depot for LTN trains to pick anything up after leaving a requester.
Though I get your mod kinda exists for those who can't figure out cleaning trains in depots only requires one inserter and active provider chest per wagon, so that assumption might be fair to make.

Redirecting trains LTN has already picked for a new delivery will cause problems. Thanks for letting me know, now I don't have to waste hours figuring out bug reports when your mod is active.

Only trains in transit between requester and depot with "Delivery completes at requester" enabled are truly safe to remove from LTN. 
With any other combination LTN has tracking going on for a train and will run into delivery time out.

**Comment by keombre** [comment]
The original reason behind cleanup is to void fluids in large mod-packs, where it's just not possible to fit all the pumps for different fluids in depots. Item processing is just a nice side-effect.

> Thanks for letting me know, now I don't have to waste hours figuring out bug reports when your mod is active.

You're welcome :D

> Only trains in transit between requester and depot are truly safe to remove from LTN.

Good to know, this saves me a lot of work too.
So to ease debugging when both of our mods are active, here is what cleanup does:
 - If LTN raises `on_requester_remaining_cargo`, cleanup will plan a new schedule, clean the train and send it back to the depot.
 - If LTN raises `on_delivery_failed`, cleanup will again try to clean the train (only if it exists) and then send it to the depot.

One last thing, is it safe to remove a train from LTN if it's parked at a depot (without any scheduled delivery)?

**Comment by keombre** [comment]
> "Delivery completes at requester" resets schedules leaving requester

I assumed it depended on when you raise the `remaining_cargo` event (either before or after the schedule reset). I'll look into it.

> So there is a time window where LTN can still see a train you scheduled for cleaning as still being free to pick for a new delivery.

Ok, that makes sense. In that case, I won't mess with parked trains either.

Thanks a lot for this ;)

**Comment by Yousei9** [comment]
While checking for your request I already added an alert for trains entering depots with leftovers and scripted fluid cleaning #185.
I still think it should be done properly either in depot or dedicated cleaning stops.

**Comment by keombre** [comment]
A little update.
`raise_event` seems to be synchronous and blocking (eg. all event listeners must return before it returns).

So to update this issue: Could you reset the schedule before raising the event? Or do you think it might break something?
(https://github.com/Yousei9/Logistic-Train-Network/blob/master/script/train-events.lua#L252)

**Comment by Yousei9** [comment]
For LTN itself it makes no difference when I reset the schedule.
Other mods listening to on_delivery_completed_event might expect the schedule before reset, though I can't see what they'd do with it when I'm about to potentially overwrite it.

**Comment by Yousei9** [comment]
If 1f6d63e fixes schedule being overwritten I'd close this issue.

**Comment by keombre** [comment]
Amazing, thanks again!
