### ISSUE TITLE
Please stop pulling releases.

### ISSUE THREAD

**Issue by Distortions81** [Yousei9/Logistic-Train-Network#257]
Please stop pulling releases.
This constantly breaks multiplayer servers, making it so no one can connect.

If it continues, I will probably just pull LTN from all my servers.

**Comment by Distortions81** [comment]
I do not want to constantly update mods. We have had mod updates break maps with 1000s of hours on them, and had to revert back to older saves... sometimes losing days or weeks of progress.

**Comment by Distortions81** [comment]
![image](https://user-images.githubusercontent.com/33408758/111914523-f26d0f00-8a37-11eb-8953-7dd355162be1.png)

**Comment by Yousei9** [comment]
Not a bug.

Old versions will be removed after 1-2 weeks from mod portal to 
a) keep the download list clean 
b) enforce old versions being unsupported
