### ISSUE TITLE
Help - different mod ?

### ISSUE THREAD

**Issue by SGZ-Creations** [Yousei9/Logistic-Train-Network#258]
https://mods.factorio.com/mod/ltn-cleanup/discussion/605f80fbe013ddefb30ef885

Asking as of  it uses your mod tho I am not sure if there's a way to implement the idea on post

**Comment by Yousei9** [comment]
You already find your cleaning stops by name.
I'd expand on that, any item/fluid a stop is able to clean must be in the stop name. Stops without any additional info are treated as universal cleaner.

**Comment by SGZ-Creations** [comment]
yes yes. I was wondering if the mod I linked could have the thing move to an combinator tho from understanding he/she don't know how to do so.
