### ISSUE TITLE
Translation to Russian. Перевод на русский

### ISSUE THREAD

**Issue by Assisstent** [Yousei9/Logistic-Train-Network#260]
Перевод мода на русский язык за моим авторством. Рекомендую ознакомиться и добавить в архив
[ru.zip](https://github.com/Yousei9/Logistic-Train-Network/files/6289401/ru.zip)

**Comment by Yousei9** [comment]
1) not a bug
2) Russian translation for LTN is available here: https://mods.factorio.com/mod/LTN_Language_Pack
