### ISSUE TITLE
additional message

### ISSUE THREAD

**Issue by LoneWolfProductions** [Yousei9/Logistic-Train-Network#262]
when a station doesnt has enough materials or does not exist the message

"No station supplying 'foo' found in networks xxxxx"

could these be split so that when there is a station with not enough materials it would show something like
"Not enough resources in providing station(s)"
when resources are low but at least one station is found.
and
"No station supplying 'foo' found in networks xxxxx"
for when there is acctually no station to be found?

right now its always a guess as i'm playing py and have hundreds of stations so a clear message of wheter the station is under performing or non existing would be nice.

Thank you for your time.

**Comment by Yousei9** [comment]
No, LTN only keeps track of items/fluids above thresholds.
Keeping track of every single item at every station would just bloat tables making sorting needlessly slower.

**Comment by LoneWolfProductions** [comment]
oh ok,
i thought when you where reading/checking the treshold at each station that info was easely available.

thanks for your time.
(nice mod btw :p)

**Comment by Yousei9** [comment]
At that point it is there, just not saved into my internal data structure for performance.

**Comment by LoneWolfProductions** [comment]
ok understandeble. it was just a question/suggestion.

Again, Thanks for your time.
