### ISSUE TITLE
Enhancement: Include 'alert' notifications in chat logs

### ISSUE THREAD

**Issue by JMatthewman** [Yousei9/Logistic-Train-Network#263]
It currently appears that the alerts shown in the Factorio Alert categories such as train left station missing cargo, with leftover cargo, with unscheduled cargo etc are only shown in the alert section, and are not output to the chat log, even with the most verbose message level configured.

It would be very useful for these to also be output to text chat as well, so that you can look back at this detail when diagnosing issues, rather than having to notice these in the short period that they're shown, and remember the details. This solves the problem raised in #229

**Comment by Yousei9** [comment]
Enable debug log or install LTN Manager for in depth analysis.
