### ISSUE TITLE
Help - Global setting: "Depot fluid removal limit"

### ISSUE THREAD

**Issue by masonanders** [Yousei9/Logistic-Train-Network#269]
We noticed this setting in the game menu while looking for a solution to our fluid wagons holding onto contents and infecting other pumps. I found no reference to the configuration in the mod's manual nor did I find any on Reddit. We've tried several inputs from 0-1000000000 but nothing seems to change and trains leave depots with fluid still in the wagons. Are we using this setting incorrectly?

https://github.com/Yousei9/Logistic-Train-Network/blob/dbb2de05583d02687b37cc866543fa5295627733/settings.lua#L146

**Comment by Yousei9** [comment]
Thanks for reporting.
I've copied the setting description from localization to the forum post.
A copy paste error prevented changes to ltn-depot-fluid-cleaning from being applied.
