### ISSUE TITLE
LTN does doing stupied addition math when used over one circuit wire

### ISSUE THREAD

**Issue by Chaoschaot232** [Yousei9/Logistic-Train-Network#270]
LTN Version: 1.16.3
Factorio Version: 1.1.36

Problem: When attching the green wire from the combinator to the LTN's input to assign some values like throughput, max trains and so on it does rly stupied math if from another combinator signals are coming in.

Means, if there are 2 LTN's requesting 25k and 75k of cruid oil while the limit of 800k cruid oil isn't reached and all is hooked up to the green wire it adds all the values from both combinators, ending up in thinking that there is a train of min/max lenght of 6 which shouldn't happen here. Networksettings seems then also to be merged (192 + 3 = 195)

Normaly this shouldn't happen and I wonder why this happens as I assume that every LTN signal send out has it's own special ID to prevent mixups like it happened on my side (this is what I would normaly do to prevent mixups ... assigning UIDs to everything)

Screens:

https://cdn.discordapp.com/attachments/231518135231053825/865171557906645052/unknown.png
https://cdn.discordapp.com/attachments/231518135231053825/865171766891511818/unknown.png
https://cdn.discordapp.com/attachments/231518135231053825/865172269801537546/unknown.png
https://cdn.discordapp.com/attachments/231518135231053825/865172362214375454/unknown.png

**Comment by Yousei9** [comment]
Read up on how circuit network works here: https://wiki.factorio.com/Circuit_network
Then check your circuit.
