### ISSUE TITLE
wrong delivery fix

### ISSUE THREAD

**Issue by ra81** [Yousei9/Logistic-Train-Network#271]
**Bug is in this code:**

if totalStacks - loadingList[i].stacks < trainInventorySize then
          -- remove stacks until it fits in train
          loadingList[i].stacks = loadingList[i].stacks - (totalStacks - trainInventorySize)
          totalStacks = trainInventorySize
          local newcount = loadingList[i].stacks * game.item_prototypes[loadingList[i].name].stack_size
          loadingList[i].count = newcount
          break
        else
          -- remove item and try again
          totalStacks = totalStacks - loadingList[i].stacks
          table.remove(loadingList, i)
 end

**To Reproduce**  
set provider station locked slots to 1
set requester station  request like {medium-electric-pole = 1900 (38 stacks), pipe=5, inserter=5}
in some situations we will get 38 stacks of poles and 1 full stack of pipe or inserter.

change 
loadingList[i].count = newcount
to
loadingList[i].count = math.min(newcount, loadingList[i].count)

this will fix the bug

**LTN version**  
1.16.0

**Log file**

**Comment by Yousei9** [comment]
Sorry, but I can't reproduce that effect.
With your setup I always get schedules for 1900 poles and 5 inserters.

**Comment by ra81** [comment]
here we have 2 screenshots and my save file with 2 setups. Full and simple. Both of them from start makes wrong delivery (see screens). Requester station is on the right side.

Screenshots:
https://img001.prntscr.com/file/img001/AxdUP590Sp2oVJaM2Zz-gg.jpg
https://img001.prntscr.com/file/img001/lEak1zczR_GRuO5tu1NsdQ.jpg

SAVE file:
https://dropmefiles.com/n1AuR

tested on last LTN with factorio 1.1.50
required mods:  aai-containers_0.2.10, LTN_Combinator_Modernized_1.0.10, LogisticTrainNetwork_1.16.7

**Comment by Yousei9** [comment]
Sorry for the long delay.
