### ISSUE TITLE
Trains approaching LTN stops the wrong way on bidirectional rail

### ISSUE THREAD

**Issue by robot256** [Yousei9/Logistic-Train-Network#275]
**Error message or bug description**  
When an LTN stop is placed on a bidirectional rail, it is possible for a train to path to the LTN-created temporary stop from the wrong direction, after which it has to go turn around and potentially enter the wrong LTN stop.

**Suggested Fix**  
Use the new API feature added in Factorio 1.1.43 to include [`rail_direction`](https://lua-api.factorio.com/latest/Concepts.html#TrainScheduleRecord) in the script-assigned temporary schedule records, to ensure the train approaches the temporary stop rail segment from the same direction as the subsequent station stop.

**LTN version**  
1.16.4

**Comment by robot256** [comment]
Apologies if this is already in the works, I realize you might have been in the discussion leading to the addition of the `rail_direction` parameter.

**Comment by Yousei9** [comment]
More of an enhancement than a bug.
I haven't been actively participating in Factorio modding for 2 years.

**Comment by mrvn** [comment]
That actually breaks bi-directional stations where you have stops with the same name on both sides of the rail. Before the train would go to the rail on the shortest path and then pick one of the two stations to unload.

Coming from the wrong direction is used as a feature there.

The use of rail_direction should be configurable or maybe even be a signal for the stop.

**Comment by robot256** [comment]
The only time it would be useful is if there are two stations with the same name directly opposite each other, right?  But it would also be dependent on your setup whether the it matters which side gets the items, even if they were the same name.  And I assume in your ambidextrous case you get warnings/messages when it stops at the "wrong" one.

**Comment by Yousei9** [comment]
I guess in that specific case disabling temp stops altogether would be more helpful.

**Comment by robot256** [comment]
I recently found it's pretty easy to make a separate mod that alters LTN-assigned schedules as they are created, without changing anything in LTN.  Making one to remove temp stops for mrvn might be the safest way to go (with a big disclaimer on it of course).

**Comment by Yousei9** [comment]
Adding a temp stop option to LTN itself is no problem either.
however, before I release an option that could cripple careless players games, I'd like to know if it'd even be useful for mrvn's problem.

**Comment by mrvn** [comment]
Removing the temp stop doesn't get the train close enough to the pair of stations to pick only one of the two. There can be multiple pairs with the same name. Leaving the temp stop but without direction is the better option.

**Comment by mrvn** [comment]
> I recently found it's pretty easy to make a separate mod that alters LTN-assigned schedules as they are created, without changing anything in LTN. Making one to remove temp stops for mrvn might be the safest way to go (with a big disclaimer on it of course).

How do you do that? As in what is the safe way to do that so it doesn't interfere with LTN. In ltn-cleanup there are some comments about changes to the schedule breaking stuff so it can't always redirect trains to remove leftover items.

**Comment by Yousei9** [comment]
Once created LTN does not touch schedules.
Register to the LTN event on_dispatcher_updated and change schedules however you need.

**Comment by robot256** [comment]
Got it working:  https://github.com/robot256/LtnTempStopOptions
Three different modes to choose from.  Haven't tested it with ltn-cleanup, so that might break things.

**Comment by mrvn** [comment]
@robot256 Stops on the same rail makes little sense. That's basically 2 separate stations. Only makes sense to consider it one station if the 2 stops share buffer chests. So your "smart" option needs a bit more work. One thing I considered is checking for a station with the same name in the same rail segment. I don't have any signals between the stops in my setups.

**Comment by mrvn** [comment]
> Once created LTN does not touch schedules. Register to the LTN event on_dispatcher_updated and change schedules however you need.

'train-events.lua: 100' resets the schedule without raising on_dispatcher_updated.

ltn-cleanup needs to modify the schedule after delivery completed or failed. If the train has items left (or is low on fuel) it adds new stops to clean up the mess (or refuel). It listens to both the completed and failed events for this. What it can't cover is trains entering the depot without delivery (with delivery was fixed above). Maybe there should be an on_train_idle event when a train enters the depot?

**Comment by Yousei9** [comment]
1) requests for expanding the API should not go in an already resolved bug report
2) that's schedule reset when trains return to depot and has no reason to raise any event called on_delivery_*
3) considering what ltn-cleanup does monitoring depots should be part for the course
4) it's not line 100, but [line 110-112.](https://github.com/Yousei9/Logistic-Train-Network/blob/a670be6faa454dca41be603d687335fd47a6b7f7/script/train-events.lua#L110)
