### ISSUE TITLE
Enhancement: Interface to mark trains as arrived [discussion]

### ISSUE THREAD

**Issue by robot256** [Yousei9/Logistic-Train-Network#278]
A remote interface function to execute the `TrainArrives()` function for a given Train and TrainStop, particularly for a different TrainStop than the one the Train is actually stopped in.

For unloading stations with more than one stop, of the same name and general location, it can be desired that only one request be generated, and mark that request as satisfied when a train arrives at either of the two stops.  This can be done with an add-on mod that provides a "proxy station".  When a train bound for an LTN stop instead arrives at a proxy stop with the same name and/or a linking signal, the add-on mod invokes `TrainArrives` for the host LTN stop.  Once the train is marked as having arrived at the LTN stop (even if it is at the proxy stop), the delivery will complete as usual when the train leaves the proxy stop.  Thus the pair of stops behaves as one LTN stop with two physical locations.

[Note: I understand this is a convoluted solution to a niche problem, one that I don't personally have a need for.  I spent a week working on it for other reasons and wanted to share it here for discussion.]

**Comment by robot256** [comment]
@mrvn I think this would be a better solution than having ltn-cleanup hijack trains out of the depot.  The author of ltn-cleanup mentions why this is a bad idea in [this thread.](https://mods.factorio.com/mod/ltn-cleanup/discussion/60ad6205b9c843baf0be6c11)  Plus it would make LTN Manager statistics correct.  It will work as long as you only allow one of the LTN+Proxy stops to be occupied at a time.

The same behavior could be incorporated into LTN itself I suppose, perhaps with a "station link" signal with the same number going to both of them.  But that is more changes to the internals of LTN than my suggestion requires.

**Comment by Yousei9** [comment]
Here's my unfiltered thoughts on the use cases I heard for such proposals so far:

**Bidirectional stations**
- Only need a single train stop to work, why bother with 2? 
- Even with stops on both sides train composition would be different between them e.g. <L<LCL> vs <LCL>L>.
- RoRo are much better anyway

**manually balancing stops**
- Why are you using LTN!?
Either let LTN do balancing, or don't use LTN

**ltn-cleanup**
- The whole concept of ltn-cleanup makes no sense, trains should be cleaned at the depot.

Unless you can convince me of any application that is generally useful and not just some weird edge case only 1 or 2 players will ever use and it's worth both my time implementing and testing as well as decreasing performance for everyone using LTN "as intended" my answer is no.

**Comment by robot256** [comment]
The idea of the remote interface was to make it transparent to users that do not install the add-on mod.  But I have to agree with your points, and I appreciate the fact that LTN stays simple and powerful thanks to your judgement.  I also think people should branch out and use other scheduling mods for their weird ideas--there are a lot of them.
