### ISSUE TITLE
Trains not clearing schedules, as of November update

### ISSUE THREAD

**Issue by CricketBr** [Yousei9/Logistic-Train-Network#279]
Worked fine until 1.16.4 or maybe 1.16.5. Still broken in 1.16.6. Playing with SeaBlock meta pack, and several other mods, but none that I think affect trains.

Already checked that Dispatcher is turned on. Deliveries complete at requester False (default). Depots reset filters True (Default).

More info (another user with similar problem) on Reddit:
https://www.reddit.com/r/factorio/comments/qv7rqu/ltn_train_picking_resources_at_wrong_station/

**Log file**
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/7548191/factorio-current.log)

**Comment by Yousei9** [comment]
Schedule clearing works fine for me.
Post a LTN only save with the issue.

The reddit post is an entirely different issue.

**Comment by CricketBr** [comment]
You're right, it works with just LTN, and with the other LTN-related mods that are in my main game. Something must else must be interfering with the schedule reset, but I've no clue what it might be.

**Comment by Yousei9** [comment]
I'm not seeing any mod I know to mess with schedules. Try activating mods one by one until your currently working test save breaks.

**Comment by CricketBr** [comment]
The working save is just LTN. The broken one is SeaBlock. That test will take a while. I might try reverting to the summer LTN version and seeing what happens.

**Comment by CricketBr** [comment]
Looks like it was LTN Manager. I gave the old save one more chance before trying to revert LTN, and LTN Manager threw a non-recoverable error this morning, with rev 0.4.0. No clue what changed overnight. LTN Manager 0.4.2 seems to work. It looks like they updated it a few times this week.

I'll make a bigger "Let all updates wait a week before installing" sign for my desk.

Thanks for your help!

**Comment by CricketBr** [comment]
Update: Was user error. I added a set of depots and mis-remembered the instructions. Put "depot" in name, but didn't set "depot=1." Knowing it wasn't a mod conflict, and seeing more updates to LTN Manager, encouraged me to open the file one more time. Thanks!
