### ISSUE TITLE
LTN crashin on station arrival

### ISSUE THREAD

**Issue by akdude2000** [Yousei9/Logistic-Train-Network#282]
Error while running event TrainWagonCombinators::on_train_changed_state (ID 24)
__TrainWagonCombinators__/wagonreader/wagonreader.lua:454: attempt to index local 'stop' (a nil value)
stack traceback:
	__TrainWagonCombinators__/wagonreader/wagonreader.lua:454: in function <__TrainWagonCombinators__/wagonreader/wagonreader.lua:434>
 i set up a small system with on train with one wagon and one locomotive as told to in this video 
https://www.youtube.com/watch?v=bpfVzfWeqj8&
minus the filter inserters, and with iron ore
![20211205140324_1](https://user-images.githubusercontent.com/71792796/144765986-0a1a772b-4b27-4f9c-ad50-91f67ea16f81.jpg)
![20211205140322_1](https://user-images.githubusercontent.com/71792796/144765990-083ab3d6-b64f-4e5a-a1f3-d2ca1f6c367c.jpg)
**To Reproduce**
i have a depot off screen just set to depot, i then sent a single train to the depot, it was assigned to deliver iron ore, and the moment it arrived at the LTN station i got that error message

**LTN version**
1.16.3

**Log file**
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/7656916/factorio-current.log)

**Comment by Yousei9** [comment]
Not an LTN error.

> Error while running event TrainWagonCombinators::on_train_changed_state (ID 24)
Read the error message.
