### ISSUE TITLE
Just Queastion

### ISSUE THREAD

**Issue by SGZ-Creations** [Yousei9/Logistic-Train-Network#286]
![image](https://user-images.githubusercontent.com/59801736/154478390-a328d3e5-7794-4ba7-93cb-db197cf23c9c.png)

On image it says inserters get stck can u explain furter ? since what i want to know is not exaclty mentioned tho i suspect it's the same as they are based on same item. & that is would loader aslo be efected? and waht dose it realy mean

**Comment by Yousei9** [comment]
MiniLoaders use hidden inserters, so yes they will behave exactly the same.

**Comment by SGZ-Creations** [comment]
Ok. Tho waht u mean by getting stuck ?

**Comment by Yousei9** [comment]
Holding items on the track.
It will be inserted in the next possible inventory, aka the next train stopping there.

**Comment by SGZ-Creations** [comment]
ty
