### ISSUE TITLE
new crash k2 se ++

### ISSUE THREAD

**Issue by n0t49a1n** [Yousei9/Logistic-Train-Network#289]
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:595: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	__LtnManager__/scripts/ltn-data.lua:595: in function 'callback'
	__flib__/table.lua:249: in function <__flib__/table.lua:221>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1077: in function 'iterate'
	__LtnManager__/control.lua:212: in function <__LtnManager__/control.lua:197>

**To Reproduce**
was no were near any ltn

**LTN version**
0.4.12

`457.936 Info ClientMultiplayerManager.cpp:786: Received mapReadyForDownload
 457.936 Downloading file C:\Users\ashpe\AppData\Roaming\Factorio\temp\mp-download.zip (57609685 B, 114533 blocks)
 457.945 Info ClientMultiplayerManager.cpp:610: UpdateTick(4294967295) changing state from(ConnectedWaitingForMap) to(ConnectedDownloadingMap)
 460.356 Finished download (2 s, 57.6 MB, 23.9 MB/s)
 460.455 Info ClientMultiplayerManager.cpp:766: updateTick(4294967295) map download finished creating scenario
 460.456 Info ClientMultiplayerManager.cpp:610: UpdateTick(4294967295) changing state from(ConnectedDownloadingMap) to(ConnectedLoadingMap)
 460.456 Loading map C:\Users\ashpe\AppData\Roaming\Factorio\temp\mp-download.zip: 57609685 bytes.
 460.519 Loading level.dat: 580525497 bytes.
 460.523 Info Scenario.cpp:199: Map version 1.1.57-1
 486.591 Loading blueprint storage: Local timestamp 1651340002, Cloud timestamp 1651340002
 492.692 Loading script.dat: 23052046 bytes.
 492.697 Checksum for script C:/Users/ashpe/AppData/Roaming/Factorio/temp/currently-playing/control.lua: 2860867080
 492.702 Checksum for script __railloader__/control.lua: 1656441273
 492.704 Checksum for script __aai-signal-transmission__/control.lua: 2864667130
 492.706 Checksum for script __AfraidOfTheDark__/control.lua: 2322376383
 492.711 Checksum for script __AutoDeconstruct__/control.lua: 407505311
 492.713 Checksum for script __Enhanced_Map_Colors__/control.lua: 3239044234
 492.715 Script @__even-distribution__/framework.lua:72: 0 [ED] Initializing framework... DEBUG = false
 492.715 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering custom scripts...
 492.715 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: metatables
 492.715 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: util
 492.715 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: helpers
 492.716 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: setup
 492.717 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: remote
 492.718 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: visuals
 492.718 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: gui-tools
 492.719 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: drag
 492.720 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: cleanup
 492.720 Script @__even-distribution__/framework.lua:72: 0 [ED] GUI-Script: settings-gui
 492.722 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering default event handlers...
 492.723 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering custom inputs...
 492.723 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: inventory-cleanup   event: on_inventory_cleanup
 492.723 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: fast-entity-transfer-hook   event: on_fast_entity_transfer_hook
 492.723 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: fast-entity-split-hook   event: on_fast_entity_split_hook
 492.725 Script @__even-distribution__/framework.lua:72: 0 [ED] Successfully initialized
 492.725 Checksum for script __even-distribution__/control.lua: 850894597
 492.732 Checksum for script __Factorissimo2__/control.lua: 5336933
 492.737 Checksum for script __FactorySearch__/control.lua: 1018908511
 492.742 Checksum for script __factory_modules__/control.lua: 3391498587
 492.743 Checksum for script __far-reach__/control.lua: 2302075386
 492.745 Checksum for script __FluidWagonColorMask__/control.lua: 4104764473
 492.763 Checksum for script __FNEI__/control.lua: 930362669
 492.764 Checksum for script __Hovercrafts__/control.lua: 3234473557
 492.766 Checksum for script __inbuilt_lighting__/control.lua: 337112260
 492.768 Checksum for script __informatron__/control.lua: 791590929
 492.773 Checksum for script __jetpack__/control.lua: 3506929631
 492.775 Checksum for script __Load-Furn-2__/control.lua: 1768708946
 492.780 Checksum for script __Mining_Drones__/control.lua: 4112820248
 492.785 Checksum for script __production-monitor__/control.lua: 87108070
 492.787 Checksum for script __robot_attrition__/control.lua: 540612876
 492.788 Checksum for script __SantasNixieTubeDisplay__/control.lua: 1054281123
 492.793 Checksum for script __shield-projector__/control.lua: 2372368545
 492.794 Checksum for script __space-exploration-graphics__/control.lua: 17466373
 492.795 Checksum for script __space-exploration-graphics-4__/control.lua: 17466373
 492.804 Checksum for script __Todo-List__/control.lua: 3829494964
 492.806 Checksum for script __train-trails__/control.lua: 288222916
 492.810 Checksum for script __Wireless_Circuit_Network__/control.lua: 1442103153
 492.811 Checksum for script __zoom-out__/control.lua: 3557337913
 492.814 Checksum for script __aai-industry__/control.lua: 1216366203
 492.880 Checksum for script __Automatic_Train_Painter__/control.lua: 3733143531
 492.918 Checksum for script __factoryplanner__/control.lua: 2392196516
 492.926 Checksum for script __LogisticTrainNetwork__/control.lua: 683205184
 492.927 Checksum for script __automatic-station-painter-continued__/control.lua: 498840276
 492.930 Checksum for script __ltn-cleanup__/control.lua: 2080544443
 492.940 Checksum for script __LTN_Combinator_Modernized__/control.lua: 3106249854
 492.941 Checksum for script __reverse-factory__/control.lua: 2747200419
 492.942 Checksum for script __robotworld-continued__/control.lua: 2159043458
 493.075 Checksum for script __space-exploration__/control.lua: 3778429285
 493.084 Checksum for script __Constructron-Continued__/control.lua: 438489749
 493.099 Checksum for script __Krastorio2__/control.lua: 2420175176
 493.110 Checksum for script __LtnManager__/control.lua: 2015870130
 493.113 Checksum for script __Rocket-Silo-Construction__/control.lua: 895359617
 493.122 Checksum for script __space-factorissimo-updated__/control.lua: 2314491491
 493.124 Checksum for script __spidertron-extended__/control.lua: 3330112913
 493.128 Checksum for script __GUI_Unifyer__/control.lua: 2611964224
 493.129 Checksum for script __krastorio2_extended_endgame__/control.lua: 1296597204
 493.135 Checksum for script __miniloader__/control.lua: 4290399381
 493.136 Checksum for script __space-exploration-postprocess__/control.lua: 2285501127
 493.146 Checksum for script __RateCalculator__/control.lua: 1527143015
 494.542 Info ClientMultiplayerManager.cpp:610: UpdateTick(77980362) changing state from(ConnectedLoadingMap) to(TryingToCatchUp)
 533.475 Info ClientMultiplayerManager.cpp:610: UpdateTick(77984741) changing state from(TryingToCatchUp) to(WaitingForCommandToStartSendingTickClosures)
 533.536 Info ClientMultiplayerManager.cpp:610: UpdateTick(77984741) changing state from(WaitingForCommandToStartSendingTickClosures) to(InGame)
 533.570 Info GameActionHandler.cpp:5000: UpdateTick (77984743) processed PlayerJoinGame peerID(1) playerIndex(0) mode(connect) 
 538.361 Info ClientSynchronizer.cpp:335: Latency changed to (112)
 547.793 Info ClientSynchronizer.cpp:335: Latency changed to (137)
 562.792 Info ClientSynchronizer.cpp:335: Latency changed to (97)
 567.790 Info ClientSynchronizer.cpp:335: Latency changed to (36)
 572.796 Info ClientSynchronizer.cpp:335: Latency changed to (18)
 577.804 Info ClientSynchronizer.cpp:335: Latency changed to (10)
 582.803 Info ClientSynchronizer.cpp:335: Latency changed to (4)
 587.803 Info ClientSynchronizer.cpp:335: Latency changed to (6)
 637.801 Info ClientSynchronizer.cpp:335: Latency changed to (7)
 682.803 Info ClientSynchronizer.cpp:335: Latency changed to (8)
 737.794 Info ClientSynchronizer.cpp:335: Latency changed to (9)
 847.860 Info ClientSynchronizer.cpp:335: Latency changed to (8)
 911.956 Error MainLoop.cpp:1284: Exception at tick 78007442: The mod LTN Manager (0.4.12) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:595: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	__LtnManager__/scripts/ltn-data.lua:595: in function 'callback'
	__flib__/table.lua:249: in function <__flib__/table.lua:221>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1077: in function 'iterate'
	__LtnManager__/control.lua:212: in function <__LtnManager__/control.lua:197>
 911.956 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "The mod LTN Manager (0.4.12) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:595: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	__LtnManager__/scripts/ltn-data.lua:595: in function 'callback'
	__flib__/table.lua:249: in function <__flib__/table.lua:221>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1077: in function 'iterate'
	__LtnManager__/control.lua:212: in function <__LtnManager__/control.lua:197>"
 911.956 Info ClientMultiplayerManager.cpp:610: UpdateTick(78007442) changing state from(InGame) to(Failed)`

**Comment by Yousei9** [comment]
Please read the error, that's a bug from LTN Manager not LTN

**Comment by n0t49a1n** [comment]
omg im toxic please ignore/del this
