### ISSUE TITLE
Factorio Alerts setting in Linux

### ISSUE THREAD

**Issue by zepanv** [Yousei9/Logistic-Train-Network#290]
**Error message or bug description**
The mod setting to turn off "Factorio Alerts" does not seem to disable the alert sound when running in linux.  This same save when played on a windows OS works as expected.

**To Reproduce**
Have a delivery request be made while running factorio in linux, the alert will sound even when the option is not selected.

**LTN version**
1.16.7

**Comment by Yousei9** [comment]
If it works in windows but not linux that's a problem with the game itself.
Nothing a lua mod can fix.
