### ISSUE TITLE
Failed to load mods

### ISSUE THREAD

**Issue by therock182** [Yousei9/Logistic-Train-Network#296]
![grafik](https://user-images.githubusercontent.com/12401617/175259808-c9127e4f-950f-4459-bf23-5e167ae0ac4a.png)

i got this error on startup. do you need more information to reproduce?

**Comment by Yousei9** [comment]
> i got this error on startup. do you need more information to reproduce?

Yes, a complete factorio-current.log

**Comment by therock182** [comment]
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/8976404/factorio-current.log)

here is the log file.
