### ISSUE TITLE
Can't disable Stop Timeout

### ISSUE THREAD

**Issue by guerrieroriccardo** [Yousei9/Logistic-Train-Network#302]
**Error message or bug description** As title says, I can't disable Stop Timeout (default 120s). Even after changing the settings, the trains schedule still limit itself at 120 seconds.

**To Reproduce** I can't provide step to reproduce the issue.

**LTN version** 1.16.10
**Factorio Version** 1.1.61

Logs: [factorio-previous.log](https://github.com/Yousei9/Logistic-Train-Network/files/9426733/factorio-previous.log)

![image](https://user-images.githubusercontent.com/40391857/186722095-e3d26601-0599-4ff2-a1f0-f181c3a3fb2d.png)
![image](https://user-images.githubusercontent.com/40391857/186722460-7d91ef06-eb17-471f-a6ee-61b628715a3b.png)
LTN Version:

**Comment by Yousei9** [comment]
Only new schedules are affected when changing settings.
Existing schedules won't change.
