### ISSUE TITLE
Error loading LTN with APM

### ISSUE THREAD

**Issue by szentigrad3** [Yousei9/Logistic-Train-Network#303]
**Error message or bug description**
https://i.imgur.com/RYk1rMH.png

**Comment by Yousei9** [comment]
What mod is apm_electric_locomotive from?

**Comment by szentigrad3** [comment]
Amator Phasma's Mods (forked)

**Comment by Yousei9** [comment]
Icon for virtual signals are generated without errors with just apm_power_ldinc_0.23.06, apm_energy_addon_ldinc_0.23.02 and LogisticTrainNetwork_1.16.10.
There's only a slight graphical issue with apm_energy_addon_ldinc using a 128x128 layer while LTN uses 64x64.
But I'm not going down the rabbit whole of re-scaling icon layers again.

![2022-09-08-07-46-17-4661432](https://user-images.githubusercontent.com/8436934/189043993-3bf7220a-fa86-4c67-85dd-1477eea127a9.png)

![2022-09-08-07-46-34-5844825](https://user-images.githubusercontent.com/8436934/189043989-effd9846-f86b-47bb-8989-dfc193dcc433.png)
