### ISSUE TITLE
[1.17.1] LTN crashes when shedule is modified while train is at station (in multiplayer)

### ISSUE THREAD

**Issue by mchernykh** [Yousei9/Logistic-Train-Network#312]
game crashes
log https://pastebin.com/11StmSj1

steps to reproduce:
set requester to accept items
wait trains to be sheduled
change requester config to other items
wait train arrival to requester
while train is at station, delete all its stations in shedule one by one starting from the first

i suspect that only deletion of shedule while train is at station matters.
i have train groups and train signals mods installed.

**Comment by Yousei9** [comment]
Thanks, for reporting this.
That's some very specific circumstances to produce a crash,
