### ISSUE TITLE
[Feature Request] Option to disable output of encoded train positions

### ISSUE THREAD

**Issue by Heniker** [Yousei9/Logistic-Train-Network#313]
**TL;DR**
Add mod setting that allows to disable output of encoded train/cargo wagon positions from Logistic Train Stop Output.

**What ?**

**Why ?**
This is an advanced feature that is very rarely used in 'real world' scenarios. It clutters circuit network signals. It makes LTN harder to reason about as unsuspected player might think those signals are required for proper LTN setups.
Even though it is possible to get rid of those signals via constant combinator or bit shifting - it makes setting up train station harder than it probably needs to be.

**Comment by Yousei9** [comment]
How so?

**Comment by Yousei9** [comment]
imply

**Comment by Heniker** [comment]
> I'd love to see your statistical data over a significant amount of LTN users to make such a claim.

You know I don't have that data and that's not how Feature Requests work.

> Just ignore them

This is a poor solution for pretty much anything.

> Position signals are unique to LTN and don't interfere with anything.

They interfere with `Anything`, `Everything` combinators.

> Position Signals and Network Ids are as complicated as counting fingers.

I'm glad you think so.
