### ISSUE TITLE
Connected surfaces nil value

### ISSUE THREAD

**Issue by Reosoul** [Yousei9/Logistic-Train-Network#314]
Playing with Space Exploration and LTN. Don't see others having this issue.. 

Created a requester, provider and depot set up in space using space trains. As soon as I enable a request, the following error occurs. Same setup is used on Navis without issue.

![image](https://user-images.githubusercontent.com/48419753/209407072-c0fee25c-bb1e-4276-a7f3-63741becdffc.png)

**Comment by Yousei9** [comment]
Unless you skipped initialization or manually changed globals there's no way for `global.ConnectedSurfaces` to ever be nil.

Downgrade to LTN 1.8.0 will force another initialization.
Alternatively using `/c remote.call("logistic-train-network", "clear_all_surface_connections")` from console will reset that global too.

**Comment by Reosoul** [comment]
Thank you so much, using the command fixed it! Not sure what initial cause would have been
