### ISSUE TITLE
se 0.6.111 and ltn 1.18.4 goes error

### ISSUE THREAD

**Issue by linlinglin** [Yousei9/Logistic-Train-Network#324]
no extrea information

**Comment by Mernom** [comment]
Need to check that the train stop in question actually has an item and miable properties before giving them the fast replace group. And also check if it's not a hidden entity.

**Comment by GamyGamer** [comment]
I can confirm that after updating this mod to 1.18.4 with SE Factorio can't load. Screenshot also shows combat-mechanic-overhaul for some reason but this bug persist even without CMO.
![obraz](https://github.com/Yousei9/Logistic-Train-Network/assets/49346764/c7db035f-a0c2-427a-82fd-2af78305eeca)

**Comment by Yousei9** [comment]
Not a bug with LTN.
SE needs to make sure the property is removed after copying from base train-stop.
