### ISSUE TITLE
Incorrect behavior with boats: boats are sent to empty ports

### ISSUE THREAD

**Issue by kovan** [Yousei9/Logistic-Train-Network#339]
**Error message or bug description**

Boats are sent to providers when there are no items in the providers.

**To Reproduce**

Just set up a requester-provider port link, but don't feed the provider with cargo, just leave it. Deliveries will start being created, and they shouldn't.

**LTN version**
1.18.6

Cargo ships 0.2.6
Also Industrial Revolution 3 mod.

**Comment by 0ptera** [comment]
Please check your wiring.
Providers are only seen as such when available items exceed provide threshold.
