### ISSUE TITLE
Network id doesn't seem to be considered

### ISSUE THREAD

**Issue by Hermios** [Yousei9/Logistic-Train-Network#341]
Make sure the bug is caused by LTN and not an interface recipient

Error message or bug description
I connected my train stops per pairs to network ids. Each pair consists in 1 depot and one provider. Requesters have all id -1
But despite each pair has a specific id starting with 100, then 101, then etc. , when a train is in depot X, it can go to any provider

To Reproduce
The idea is to duplicate several pairs, consisting in one depot and one network id (same for both).
I started with 100, to ensure that each pair doesn't cover another one
first pair is directly connected to a constant combinator, with value 100
duplicate of this pair is connected to an arithmetic combinator, which add +1 to the previous arithmetic combinator output, or the constant combinator for the second pair.
Network id is connected to the lamp (input) of the train stop
Below a screenshot of the configuration:

![image](https://github.com/user-attachments/assets/cacb5e33-e0fb-4aa1-9bc6-adddc33d7fe5)

Still, trains from a depot x can go to any provider, with another network id. This regularly jams all my system of trains.

And a bigger image, in green what I expect, in red what I have:
![image](https://github.com/user-attachments/assets/3a7f1c75-bb10-4035-a553-a45c25125d43)

LTN version
1.18.6

Log file
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by 0ptera** [comment]
NetworkID is binary encoded.
Each bit represents if a Network is allowed or not.

What you told LTN is, the first Depot is valid for Networks 3, 6 and 7, the second for 1, 3, 6 and 7 and so on.
So it's working as designed.
