### ISSUE TITLE
Error while running event LtnManager::on_tick (ID 0)  

### ISSUE THREAD

**Issue by razorftw** [Yousei9/Logistic-Train-Network#342]
I'm willing to provide blueprints or config file, just let me know.

**Error message or bug description**
```
Error while running event LtnManager::on_tick (ID 0)   

LtnManager__/scripts/ltn-data.lua:271: bad argument #1 of 2 to
'ipairs' (table expected, got nil)
stack traceback:

[C]: in function 'ipairs'

LtnManager__/scripts/ltn-data.lua:271: in function 'callback'
flib__/table.lua:299: in function <flib/table.lua:271>

(...tail calls...)

LtnManager/scripts/ltn-data.lua: 1075: in function 'iterate'

LtnManager__/control.lua:223: in function

<LtnManager/control.lua:208>
```

**To Reproduce**

**Tested on:**
Singleplayer: no
Hosted Save: yes
Servers: yes

- Open Sandbox using the mod link below
- Paste a ltn train station with a combinator blueprint connected
- Click on train station
- Game Crashed

https://mods.factorio.com/mod/blueprint-sandboxes

**LTN version**
1.18.6

**Log file**
https://drive.google.com/file/d/17gvbTpruSf9xnug7jbHXqTwB1cUTVACJ/view?usp=sharing

**Comment by razorftw** [comment]
I'd like the expand on another method of reproduction,

I experienced this while hosting a save

- I pasted a blueprint while still in sandbox mod (mod link in the first message)
- opened an configured [LTN Combinator](https://mods.factorio.com/mod/LTN_Combinator_Modernized) from the blueprint
- removed the requested item 
- Opened [FNEI](https://mods.factorio.com/mod/FNEI)
- Save crashed.

**Note:**
Removing the ltn stations from the blueprint, allows the save to continue, while doing the steps above.

https://mods.factorio.com/mod/LTN_Combinator_Modernized
https://mods.factorio.com/mod/FNEI

**Comment by 0ptera** [comment]
This Git Project is only for LTN itself.
LTN Manager and LTN Combinator are managed by other authors. please report your bug there.
