### ISSUE TITLE
More trains than the station limit summoned

### ISSUE THREAD

**Issue by i-make-robots** [Yousei9/Logistic-Train-Network#343]
**Error message or bug description**
When a train in a station cannot leave LTN continues to summon trains to the station.  This leads to a traffic jam.

**To Reproduce**
Set any train in any station to manual and wait for the timeout to expire.

**Ideal solution**
Recognize that there is a train in the station and emit a warning to the user instead of summoning more trains.

**LTN version**
1.18.6

**Comment by 0ptera** [comment]
Working as intended.
A train set to manual can't be tracked.

If you want a train to stay in a station enable circuit signals and send a red signal to the train.

**Comment by i-make-robots** [comment]
So the problem is how to reproduce it?  Fine.  

A train arrives at a station but the unloaders are disabled.  The train sits with product, unmoving.  the timeout is set to maximum (36000?).  Meanwhile, more trains are summoned, in spite of the station being at its limit.

Another way I've seen it is with miniloaders that are jammed with material, so they're not technically disabled but the belts don't move product so, again, the cars can't unload.  Or a tank has lube but the train that pulled in somehow has crude oil.  the pump fills with crude but can't push into the tank (would mix).  The train sits there until the timeout.  meanwhile, more trains arrive.

**Comment by 0ptera** [comment]
> A train arrives at a station but the unloaders are disabled. The train sits with product, unmoving. the timeout is set to maximum (36000?). Meanwhile, more trains are summoned, in spite of the station being at its limit.
> 
> Another way I've seen it is with miniloaders that are jammed with material, so they're not technically disabled but the belts don't move product so, again, the cars can't unload. Or a tank has lube but the train that pulled in somehow has crude oil. the pump fills with crude but can't push into the tank (would mix). The train sits there until the timeout. meanwhile, more trains arrive.

All those are design errors I won't account for in LTN.
Make sure unloading stations are capable of unloading a train before requesting more material.

**Comment by i-make-robots** [comment]
I'm starting to understand why LTN is the way it is.  I hope your day is a pleasant as you are.
