### ISSUE TITLE
LTN will be updated for SA?

### ISSUE THREAD

**Issue by enzain** [Yousei9/Logistic-Train-Network#345]
Helo,

LTN will be updated for SA?

Please, do it .. )

**Comment by Bezzoom** [comment]
+1

**Comment by Jvaxx** [comment]
+2

**Comment by AlanWakeKing** [comment]
+3

**Comment by shirobachi** [comment]
+4

**Comment by LiPoWeRaD** [comment]
+5

**Comment by Olivka98** [comment]
+6

**Comment by Roskoov** [comment]
+7

**Comment by davidhorac3** [comment]
+8

**Comment by Sbmhawk** [comment]
+9

**Comment by 0ptera** [comment]
Sorry to dissapoint you guys.
LTN was designed for Factorio 0.14.
While porting it over should somewhat work, Factorio 2.0 deserves a new design built from scratch.
Since I'm no longer playing Factorio, there's little chance I'll design LTN 2.0.

**Comment by blackheart3d** [comment]
Suddenly Space Age isn't going to be nearly as fun. :'(

**Comment by MrVSV** [comment]
Sad

**Comment by SyselMitY** [comment]
I cannot promise anything since I am new to Factorio modding, but I will try to port LTN to 2.0 and try to fix at least the major bugs that will (probably) arise. As I said, I am still unsure whether I am "fit for this task", or if I have the necessary time, but anything is better than not having LTN I suppose :P

**Comment by 0ptera** [comment]
> I cannot promise anything since I am new to Factorio modding, but I will try to port LTN to 2.0 and try to fix at least the major bugs that will (probably) arise. As I said, I am still unsure whether I am "fit for this task", or if I have the necessary time, but anything is better than not having LTN I suppose :P

While LTN is open source, it's not free source.
Please read [the license](https://github.com/0ptera/Logistic-Train-Network/blob/master/LICENSE.md)

**Comment by SyselMitY** [comment]
Noted. I will try the first steps in private, to see if I have a chance of succeeding, after that I will contact you about what happens next if it's ok.

**Comment by MrVSV** [comment]
> Sorry to dissapoint you guys. LTN was designed for Factorio 0.14. While porting it over should somewhat work, Factorio 2.0 deserves a new design built from scratch. Since I'm no longer playing Factorio, there's little chance I'll design LTN 2.0.

please, do it. I don't know how to play without ltn)

**Comment by enzain** [comment]
> > Sorry to dissapoint you guys. LTN was designed for Factorio 0.14. While porting it over should somewhat work, Factorio 2.0 deserves a new design built from scratch. Since I'm no longer playing Factorio, there's little chance I'll design LTN 2.0.
> 
> please, do it. I don't know how to play without ltn)

Try see new trains logic )

But yes - LTN will be fine if be updated.

**Comment by MrVSV** [comment]
> > > Sorry to dissapoint you guys. LTN was designed for Factorio 0.14. While porting it over should somewhat work, Factorio 2.0 deserves a new design built from scratch. Since I'm no longer playing Factorio, there's little chance I'll design LTN 2.0.
> > 
> > please, do it. I don't know how to play without ltn)
> 
> Try see new trains logic )
> 
> But yes - LTN will be fine if be updated.

I couldn't even learn how to use the old one. And now nothing is clear there at all)

**Comment by SyselMitY** [comment]
Oh wow, that mod totally flew under my radar, thanks for mentioning it. I will look into it tomorrow, it doesn't make sense to port LTN if Cybersyn is a good alternative, even if it means people have to rebuild all stations.
