### ISSUE TITLE
UPDATE TO SPACE AGE PLEASE!!! I CAN'T PLAY WITHOUT LTN!!!

### ISSUE THREAD

**Issue by intelegenter** [Yousei9/Logistic-Train-Network#346]
**TL;DR**
I really neeed LTN update to space age!

**What ?**
The Update to factorio v2!

**Why ?**
Because it's so terribly painful, so incredibly inconvenient, so sad, so depressing to play Factorio without LTN that it makes me depressed!

**Comment by SuperPyroManiac** [comment]
Author stated they are not updating this, and they were off-putting with their license rules about others updating it. 
**A solid alternative is https://mods.factorio.com/mod/cybersyn**

**Comment by intelegenter** [comment]
> Author stated they are not updating this, and they were off-putting with their license rules about others updating it. **A solid alternative is https://mods.factorio.com/mod/cybersyn**

Thank you very much!!!

**Comment by kuxynator** [comment]
> not updating this, and they were off-putting with their license rules about others updating it.

For what reason?

**Comment by wchristian** [comment]
They [forbid other people from forking LTN](https://github.com/0ptera/Logistic-Train-Network/blob/master/LICENSE.md) and refuse to update it because they [don't play factorio anymore](https://github.com/0ptera/Logistic-Train-Network/issues/345#issuecomment-2428770592).

**Comment by 0ptera** [comment]
> They [forbid other people from forking LTN](https://github.com/0ptera/Logistic-Train-Network/blob/master/LICENSE.md) and refuse to update it because they [don't play factorio anymore](https://github.com/0ptera/Logistic-Train-Network/issues/345#issuecomment-2428770592).

Thanks for linking my License, but have you actually read it?
It only prevents redistribution without my consent.

So far neither [SyselMitY](https://github.com/SyselMitY) nor anyone else has come up to me and asked to properly take over LTN.

**Comment by wchristian** [comment]
Well, you might wanna consider how you come across then. Someone said they'd try and fix it up and your first response was to rebuff it without further explanation.

If you're truly willing to give it up to somebody else, but don't want to grant blanket license, maybe consider writing up what you consider necessary to grant someone license, so people can decide whether it's worth making the effort and don't have to worry about you telling them to go away for a random reason. :)

**Comment by kuxynator** [comment]
Communication is sometimes difficult, and also read ;-)
It is perfectly understandable that someone wants to be asked. 

So I'll answer my own question :
  **For the reason that forks do not suddenly appear in uncontrollable quantities**
  
  @0ptera thanks for this great mod and all the work you've put into it <3

**Comment by tburrows13** [comment]
> Well, you might wanna consider how you come across then. Someone said they'd try and fix it up and your first response was to rebuff it without further explanation.
> 
> If you're truly willing to give it up to somebody else, but don't want to grant blanket license, maybe consider writing up what you consider necessary to grant someone license, so people can decide whether it's worth making the effort and don't have to worry about you telling them to go away for a random reason. :)

0ptera said to read the license, and the license says "Exceptions to the no modification rule may be granted after written requests."

**Comment by wchristian** [comment]
> 0ptera said to read the license, and the license says "Exceptions to the no modification rule may be granted after written requests."

Yes and this adds no new information that hadn't already been read and taken into account by my words pointing out that there's a big unknown that can easily be addressed and remains present in your very curt post. So: Why tell me?

(In fact, the bit you quoted is not very meaningful, since that is already how all licenses work.)

**Comment by Sharparam** [comment]
> since that is already how all licenses work

Very much not. (FL)OSS licenses allow you to modify and (re-)distribute without having to first request permission from the author.

**Comment by wchristian** [comment]
> Very much not. (FL)OSS licenses allow you to modify and (re-)distribute without having to first request permission from the author.

The quoted bit says "exceptions may be granted on request". That is how literally all licenses work. If a license does not have a "no modification rule", then of course there is no exception to **that** to be granted, but even then the general case remains true:

The license states what you may do without asking. If you want to do something it does not state, you have to ask.

Please. Open source development is my day job.

The important bit is whether there is enough ancillary information available to successfully dispel the chilling effect a restrictive license causes in the first place.

**Comment by Sharparam** [comment]
> The license states what you may do without asking. If you want to do something it does not state, you have to ask.

Yes, but that is not what your previous comment communicated.

> Please. Open source development is my day job.

This statement is kinda pointless. Plenty of people with jobs in software development seem to not understand licenses so someone working in that field has no bearing on their license knowledge.

If you were a lawyer that would be different.

----

I have to wonder if the license in this project even works as written. It has a clause about implicitly transferring code ownership without any kind of explicit transfer by the original author, which I thought was impossible with current copyright law.

**Comment by wchristian** [comment]
I wrote open source, not just software development. Also, you read something into my comment that i did not communicate. I'm moderately curious how you did that, but at the same time that is also off-topic for this venue.

As for the contributor licensing, yeah, that part does nothing. https://yahoo.github.io/oss-guide/docs/resources/what-is-cla.html

**Comment by Sharparam** [comment]
> I wrote open source, not just software development.

Which is a subset of software engineering (and not like non-open source devs *don't* have to deal with licenses). Point being that someone who works with development *of any kind, **including** open source* (is that clear enough?), doesn't necessarily understand everything about licenses (they are legal documents after all). (I'll be the first to admit that and that's why I use established standard licenses instead of trying to roll my own which inevitably ends with failure unless you're a lawyer.)

But if you're going to be that pedantic about words, then I'll point out that you misquoted in your previous comment:

> The quoted bit says "exceptions may be granted on request".

No, the quoted bit says "Exceptions to the no modification rule may be granted after written requests.". (Paraphrasing is not the same as quoting.)

> Also, you read something into my comment that i did not communicate. I'm moderately curious how you did that

That just means that your comment was written ambiguously at best. But the way I read your comment was that all licenses require asking for exceptions for modification.

> but at the same time that is also off-topic for this venue

Oh definitely. It's annoying how there's never any good methods to branch off off-topic discussions on places like these.

**Comment by Hurricane-046** [comment]
I'd also very much appreciate this mod getting updated to SA. It's one of the best, if not the best Train Manager mod for Factorio.

**Comment by Atria1234** [comment]
0ptera mentioned that mod deserves a rewrite. Is it about something in perticular or just in general?

Don't get me wrong, I love myself some complete rewrite of something I indent to maintain. But if he's not intending to maintain it I don't see a reason for rewrite unless there is a list of things which are problematic.

If such list exists, could you share it @0ptera so people are more likely to succeed in getting the permission from you to update it?

Or would you be ok with someone just updating it to 2.0 without any massive rewrites?

**Comment by 0ptera** [comment]
> Or would you be ok with someone just updating it to 2.0 without any massive rewrites?

That's the one thing I'm not OK with.

LTN was written for how trains operated back in 0.14.
Meanwhile several basic assumptions have changed. For example reducing the total number of trains is far less impactful on performance than reducing travel distances.
So the whole concept of trains returning to depot after each trip reduces performance for large bases.
A much better concept would be to keep trains parked at free providers and only return to depots when no providers are free or train needs fuel or cleaning from residue.

It also supports edge cases like keeping cargo in a train, which I'd get rid of to improve performance.
If a train was guaranteed to be empty before going to a provider that'd make solving an current issues with incorrect loading trivial.

That's just what instantly comes to mind. There's probably several other things warranting a complete rewrite.

**Comment by KeinNiemand** [comment]
> Or would you be ok with someone just updating it to 2.0 without any massive rewrite

If your not going to update it at least let someone else update it what do you get from not letting anyone else update the mod update?

I absolutley need LTN so I can continue and finish my 450h modded save, while I could go back to 1.1 I can't really play without the QOL improvments in 2.0 anymore (which is why I waited for 2.0 before continueing in the first place)
Thank you for ruining my 450h save by not updating the mod or letting someone else update the mod (manually replacing all the hundreds of station to not use LTN would probably take like 100h+).

**Comment by 0ptera** [comment]
> > Or would you be ok with someone just updating it to 2.0 without any massive rewrite
> 
> If your not going to update it at least let someone else update it what do you get from not letting anyone else update the mod update?
> 
> I absolutley need LTN so I can continue and finish my 450h modded save, while I could go back to 1.1 I can't really play without the QOL improvments in 2.0 anymore (which is why I waited for 2.0 before continueing in the first place) Thank you for ruining my 450h save by not updating the mod or letting someone else update the mod (manually replacing all the hundreds of station to not use LTN would probably take like 100h+).

Entitled demands like these are what drove me away from modding in the first place.
Thanks for reminding me why I will not come back.

**Comment by Atria1234** [comment]
I wonder if there could be a mod which only thing it does is convert LTN signals and stations to Project Cybersyn, then the mod could be disabled and players can continue with Cybersyn.

Did anyone do some research about feature overlap? Is LTN subset of Cybersyn? What features are missing in Cybersyn?

**Comment by wchristian** [comment]
@0ptera quick question regarding your license, the answer to which i could not find by reading:

Which part of your license grants permission to publish a modified fork of your code to github?

Asking since a lack of such permission indicates that all of these are violating your license: https://github.com/0ptera/Logistic-Train-Network/network

**Comment by Sharparam** [comment]
@wchristian So @0ptera, by having the repo as public on GitHub, agrees to at least this in GitHub's Terms of Service: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

To quote:

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
> 
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you [adopt a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository). If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

So that *should* mean (IANAL) that as long as it's contained on GitHub, you are free to fork and work on it. But if you try to distribute anywhere outside of GitHub (like the Factorio mod portal) that would not be allowed under the custom license. (But homemade licenses rarely hold up under scrutiny.)

**Comment by wchristian** [comment]
Well, that would mean per the licenses of this one and github, anyone who wants to update LTN and desires some beta testers can upload a placeholder mod to the mod portal that points at their repository. :)

**Comment by Atria1234** [comment]
Any licence is only as strong as author's will to enforce them.

In this case it is my opinion that author is needlessly stubborn...not planning to update the mod and not allowing anyone to update it unless it is according to his specifications.

Sure, the community makes entitled demands but maybe author should look into mirror. If you released your mod when you are abandonding it, someone would step up to update it and everyone would be happy.

I'm planning to check feature overlap with Cybersyn and then either create migration mod or just update this mod to 2.0. At first for my personal use and then maybe even publish it as new mod.

**Comment by wchristian** [comment]
Alright, i see Optera has weighed in positively.

![image](https://github.com/user-attachments/assets/7384d6b6-9c7e-433c-a987-508a7e07c654)
This means people have explicit license to release modified versions of LTN to github.

Thus a placeholder release to the factorio mod portal can link to the github repository with the modified LTN, and thus facilitate outreach for testers with whom to create a version that can run on 2.0, is tested for stability, and to serve as a candidate for requesting full release permissions.

Yay. Moderately convoluted, but a healthy path out of the situation. :)

**Comment by caoliang313** [comment]
@0ptera Hello，I really need LTN,I canot play without LTN, please update it to 2.0,thanks
I have created many tutorial for LTN in bilibili, for here [https://b23.tv/cRnoQcF](url), that's very popular.

**Comment by Atria1234** [comment]
Here's first version of LTN to Cybersyn migration mod: https://mods.factorio.com/mod/LtnToCybersynMigration

There are couple of requirements (specifically that it needs you to use LTN combinator modernized mod), but from testing looks promising
