### ISSUE TITLE
Update to 2.0 via Pull Request.

### ISSUE THREAD

**Issue by subtogash** [Yousei9/Logistic-Train-Network#348]
As far as I understand, the developer forbade making changes to the mod without his approval, so why don't developers who have the desire and capabilities update LTN via pull request, because when using this method, the license doesn't seem to be violated.

**Comment by cablegunmaster** [comment]
simple, its hard to change this mod; without prior modding experience, 2.0.7 has allot of changing / breaking changes.
See; the following changelist ; https://forums.factorio.com/viewtopic.php?t=116184 . This is a huge changelist, 
And there are some breaking changes, LuaConstantCombinatorControlBehavior has changed.
Requires time, communication and effort, a few days of debugging and working on Lua, learning lua.

Figuring out why; Removed LuaConstantCombinatorControlBehavior::signals_count, set_signal() and get_signal().   is removed and how to get an alternative working.

It crashed when loading up my old Pyanadon save, 
it crashed when placing down a building in a normal save.
Shortly said, effort , time and reading.

I can see why 0ptera is not opting for porting it, it takes time.

**Comment by PSR-J0740** [comment]
I've a version that work almost perfectly. Only fluid request are not served. I haven't checked every feature yet, but I'm close.

**Comment by cablegunmaster** [comment]
I have seen, I was also working on it, on a seperate v2.0 branch  you already solved the new way of signals which they did not made a migration plan for. If 2.0 is working time to get a plan for new features =). Optera had a wishlist of new things. I would say first make 2.0 working , after that go look at the wishlist, add more people on this repository and make it more alive. but thats just me talking.

**Comment by 0ptera** [comment]
Please read the summary in https://github.com/0ptera/Logistic-Train-Network/issues/350 .

I don't want to drag outdated concepts to 2.0 with a rudimentary port.
Ideally it'd be a rewrite which won't fall under my license except for graphics.
