### ISSUE TITLE
Please allow negative priority (1.4.11)

### ISSUE THREAD

**Issue by mgravell** [Yousei9/Logistic-Train-Network#64]
In https://github.com/Yousei9/Logistic-Train-Network/commit/2c54b0bd08d2467ba9d7d8950038a1a3f878b130 you disregard negative signals, including priorities.

I've been using negative priorities to allow me to *deprioritize* a utility provider. To take a specific example of empty barrels, *most* of my stations don't specify a priority. A single provider exists that creates and supplies new barrels and has a priority of -1. This means that barrels are *when possible* taken from regular stops, only taking from the utility provider if there are none available - worked great. The other solution is to explicitly specify a provider priority at all my stations that provide barrels (by emptying them), so that it can be higher than the utility station.

This commit will prevent that from working. Please consider allowing negative priority.

**Comment by Yousei9** [comment]
I'll test negative priorities. If they work as intended I'll re-enable them in the next update.
