### ISSUE TITLE
Provider priority should not be overridden by the current number of active deliveries

### ISSUE THREAD

**Issue by Berdes** [Yousei9/Logistic-Train-Network#69]
I'm deep in a Bobs+Angels  game and I'm trying out the LTN mod. I slowly setting up a full LTN and running some tests, I noticed that I was unable to get my empty barrels to get picked up from my subfactories to get refilled because empty barrels were systematically taken from the barrel factory.

Even when setting a very high provider priority to the station providing empty barrels in the sub factories trains decided to go to the barrel factory. After reading the code, it seems that the number of active deliveries is actually more important than priority (https://github.com/Yousei9/Logistic-Train-Network/blob/master/control.lua#L791). So given that I have a single station providing all the trash (including all empty barrels) in my subfactories, I usually have many active delivery scheduled going through this station.

**Comment by Yousei9** [comment]
Yes, that is by design.
Without this trains queued up in front of prioritized providers.

You have 2 options:
1. Use higher provide thresholds and larger trains to reduce the number of trains (also helps with UPS).
2. Use more Providers.
