### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Tomirad** [Yousei9/Logistic-Train-Network#74]
If you need, I have created a Polish translation for your mod.
https://github.com/Tomirad/FactorioModsTranslationProject/tree/master/LogisticTrainNetwork_1.5.1/locale/pl

**Comment by Yousei9** [comment]
As I  only speak English and German myself and don't have the time to chase after translators nor want to use the questionable translations from google I'd prefer not to integrate any translation in my mods until they are finalized.

Feel free to host your translations as submod like the Korean translation project. https://mods.factorio.com/mods/Xagros/XMKTP
