### ISSUE TITLE
Supply or Request by distance.

### ISSUE THREAD

**Issue by pedrotk** [Yousei9/Logistic-Train-Network#75]
Making possible to make rules to make transport cargo by short or long distances.
I think this is will be great if someone want to make 2 big base, and only long trains will transport between the bases, short trains will stay inside the bases.

**Comment by Yousei9** [comment]
That already is possible by using min & max train length control signals.

**Comment by pedrotk** [comment]
Sorry, broken English, i mean distance between stations, not length of trains,

for example, if i have 2 bases, but don't wanted the short trains travel long distances just to do some short business in another base.

in my actual base, I'm using 2 different trains types, LCCL and LCCCL for separate the trains, the travel distance limit would be good.

**Comment by Yousei9** [comment]
Calculating even beeline distances is rather performance intensive and often delivers unsatisfying results.
Like said above, use train size signals to restrict trains from making certain runs.

**Comment by pedrotk** [comment]
Oh, i don't know that 
thank you for the response
