### ISSUE TITLE
Fluid delivery not outputting amount

### ISSUE THREAD

**Issue by SereneRebel** [Yousei9/Logistic-Train-Network#89]
When a train arrives to fulfil a fluid delivery the amount is not outputted from the combinator as it is with item delivery
![20171227210848_1](https://user-images.githubusercontent.com/25892745/34382499-520c2184-eb4a-11e7-89f7-b42b636accae.jpg)

**Comment by Yousei9** [comment]
The only output at the yellow combinator when unloading are
- train composition
- items to KEEP in the train

To get items to unload use inventory from stop-items to keep.
This change has been made months ago to allow simpler logic builds for 0.15

**Comment by SereneRebel** [comment]
Excellent thank you this does indeed make more sense
