### ISSUE TITLE
Update train inventory storage limit

### ISSUE THREAD

**Issue by pedrotk** [Yousei9/Logistic-Train-Network#90]
i changed the size on my cargo wagon while playing, but LTN still use the previous limit and do the same delivery, even the train have free space.

Perhaps LTN just check the limit cargo on the first start on the game?

edit1:just a question
edit2: to be more specific, i changed the _inventory_size_ of cargo wagon from factorio core, and reload my save file.

**Comment by pedrotk** [comment]
Disabled and Enabled with version 1.6.1
solved

**Comment by Yousei9** [comment]
LTN learns cargo capacities over time and saves them in global.WagonCapacity.
When you change values directly in base it won't trigger on_configuration_changed or on_init where LTN resets that lookup table.

To be save never update base or any mod directly, instead create a mod referencing to that or at least change the version number.

Moving capacity detection from global to a local array writeable during on_load would require this code to run each time a player joins a mp game:
```lua
  for _,force in pairs(game.forces) do
    local trains = force.get_trains()
    for _,train in pairs(trains) do
      for _,wagon in pairs (train.carriages) do
        WagonCapacity[wagon.name] = entity.prototype.get_inventory_size(defines.inventory.cargo_wagon) or entity.fluidbox.get_capacity[1]
      end
    end
  end
```
