### ISSUE TITLE
train.fluid_wagons and train.cargo_wagons in branch 1.6.2

### ISSUE THREAD

**Issue by thelastWallE** [Yousei9/Logistic-Train-Network#91]
Hi. I found your new branch for version 1.6.2 on github, because of the getWagonCapacity bug with the fluid wagons.
I just wanted to note that it seems that the variables are turned around for fluid and cargo wagons.
Thanks for your mod! I have fun playing with it.

https://github.com/Yousei9/Logistic-Train-Network/blob/6640684a323de8dfa91b20b73a186151c2c82ac3/control.lua#L1768

for _,wagon in pairs(train.cargo_wagons) do
      local capacity = global.WagonCapacity[wagon.name] or getCargoWagonCapacity(wagon)
      fluidCapacity = fluidCapacity + capacity
    end    
    for _,wagon in pairs(train.fluid_wagons) do
      local capacity = global.WagonCapacity[wagon.name] or getFluidWagonCapacity(wagon)
      inventorySize = inventorySize + capacity
end

**Comment by Yousei9** [comment]
Thanks for finding this derpy mistake. Those are the ones i usually spend longest to find myself.
