### ISSUE TITLE
Fluid wagons being overfilled

### ISSUE THREAD

**Issue by SereneRebel** [Yousei9/Logistic-Train-Network#94]
I have noticed with my setup i have trains with 2 fluid wagons for delivering various fluids. 

when a request is started it states 75000 units but the problem is each fluid wagon now only holds 25k each. i haven't checked in depth yet but it seems it is not taking into account the latest change in fluid wagon capacity

Factorio version 0.16.10
LTN version 1.6.2

**Comment by Yousei9** [comment]
I can only reproduce that for deliveries created in a Factorio version before 0.16.8
Deliveries created in 0.16.8 and later use the correct fluid wagon capacity.

Deliveries are not recalculated to potential new stack sizes or wagon capacities each time the configuration changes.
Changes to stack sizes and wagon capacities happen very rarely and only affect trains on their way to a provider. I think it's acceptable having trains being forced out of a station with stop timeout once after such an update.

Should it happen for you with deliveries created in 0.16.8 or later enable debug logging in mod options, generate such a delivery and send me factorio-current.log.

**Comment by SereneRebel** [comment]
After further testing i have found the mod did not update correctly and i was in fact still running 1.6.1 and since re-installing the mod it has been corrected. 
apologies for the misreport i should have checked these things first
