### ISSUE TITLE
Mod crashes when i am deconstructing rails

### ISSUE THREAD

**Issue by kamtschatka** [Yousei9/Logistic-Train-Network#95]
I used drones to deconstruct my depots and got this exception:
Error while running event LogisticTrainNetwork::on_robot_pre_mined (ID 15)
__LogisticTrainNetwork__/control.lua:689: attempt to index field '?' (a nil value)

I am running version 1.6.2 of the LTN and 0.16.15 of Factorio

**Comment by kamtschatka** [comment]
seems like this only happens, when there is currently a train in the station(and maybe only if it is not done by my own drones, but with the drones in the network, but i was not )

**Comment by Yousei9** [comment]
Deconstructing a depot with parked train works fine for me in both migrated save from 0.15 and new game.

please attach the affected save

**Comment by kamtschatka** [comment]
It is already huge and has version 0.16.6 as the current version: https://www.dropbox.com/s/m2ja9lg0jfxcben/fixed4.zip?dl=0

**Comment by Yousei9** [comment]
Fixed in 1.6.3.
